const PLAYER_STORAGE_KEY='grassstatory.v3.players';
const SETTINGS_STORAGE_KEY='grassstatory.v3.settings';
const MATCH_STORAGE_KEY='grassstatory.v3.matches';
const UPCOMING_STORAGE_KEY='grassstatory.v3.fixtures';
const defaultSettings={matchFormat:5,playersOnPitch:5,teamName:'Your Team',teamAbbr:'YTM',ageGroup:'',season:'2026/27',primaryColor:'#25df72',secondaryColor:'#0b2a38',userRole:'Parent',onboardingPrimaryColor:'#25df72',onboardingSecondaryColor:'#0b2a38',planPreview:'platinum'};
let activeMatchId=null,timerInterval=null,statsFilter='All',adjustOurIds=new Set(),adjustOpponentCount=5,batchOffIds=new Set(),batchOnIds=new Set();
const $=id=>document.getElementById(id);
const views={homeView:$('homeView'),matchesView:$('matchesView'),statsView:$('statsView'),settingsView:$('settingsView'),platinumView:$('platinumView'),matchSetupView:$('matchSetupView'),liveMatchView:$('liveMatchView'),matchReportView:$('matchReportView'),onboardingView:$('onboardingView')};
const makeId=()=>crypto.randomUUID?crypto.randomUUID():`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function loadJson(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function saveJson(k,v){localStorage.setItem(k,JSON.stringify(v))}
function loadPlayers(){return loadJson(PLAYER_STORAGE_KEY,[])}
function savePlayers(v){saveJson(PLAYER_STORAGE_KEY,v)}
function loadSettings(){return {...defaultSettings,...loadJson(SETTINGS_STORAGE_KEY,{}),planPreview:'platinum'}}
function saveSettings(v){saveJson(SETTINGS_STORAGE_KEY,v)}
function loadMatches(){return loadJson(MATCH_STORAGE_KEY,[])}
function saveMatches(v){saveJson(MATCH_STORAGE_KEY,v)}
function loadFixtures(){return loadJson(UPCOMING_STORAGE_KEY,[])}
function saveFixtures(v){saveJson(UPCOMING_STORAGE_KEY,v)}
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function cleanAbbr(v,f='TEAM'){const x=String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');return(x||f).slice(0,3)}
function derivedAbbr(name,f='OPP'){const w=String(name||'').trim().split(/\s+/).filter(Boolean);if(!w.length)return f;const c=w.join('').replace(/[^A-Za-z0-9]/g,'');if(c.length<=3)return c.toUpperCase();return cleanAbbr(w.map(x=>x[0]).join(''),f)}
function teamDisplay(){const s=loadSettings();return{name:s.teamName||'Your Team',abbr:cleanAbbr(s.teamAbbr,'YTM')}}
function positionAbbr(position){const p=String(position||'').toLowerCase();if(p.includes('goal'))return'GK';if(p.includes('def'))return'DEF';if(p.includes('mid'))return'MID';if(p.includes('strik')||p.includes('forward')||p.includes('attack'))return'ST';return'PLY';}
function playerLabel(p){return`${p.number?`#${p.number} `:''}${p.name}${p.position?` · ${p.position}`:''}`}
function cardStyle(){const s=loadSettings();return`--club-primary:${escapeHtml(s.primaryColor||'#0c7a44')};--club-secondary:${escapeHtml(s.secondaryColor||'#f4f3ec')}`}
function playerIdentityCard(p,klass='gs-player-card-v3'){const s=loadSettings(),name=String(p?.name||'Player'),pos=String(p?.position||'Player'),num=String(p?.number||'–');return`<article class="${klass}" style="${cardStyle()}"><div class="gsc-club">${escapeHtml(s.teamName||'Your Club')}</div><div class="gsc-abbr">${escapeHtml(cleanAbbr(s.teamAbbr,'TEAM'))}</div><div class="gsc-name">${escapeHtml(name.toUpperCase())}</div><div class="gsc-number">${escapeHtml(num)}</div><div class="gsc-position">${escapeHtml(pos.toUpperCase())}</div><div class="gsc-sign">${escapeHtml(name)}</div></article>`}
function playerActionTile(p,selected=false,extra=''){const s=loadSettings(),name=String(p?.name||'Player'),pos=String(p?.position||'Player'),num=String(p?.number||'–');return`<span class="gs-action-tile ${selected?'selected':''}" style="${cardStyle()}"><span class="gat-number">${escapeHtml(num)}</span><span class="gat-name">${escapeHtml(name)}</span><span class="gat-pos">${escapeHtml(pos)}</span>${selected?'<span class="gat-check">✓</span>':''}${extra}</span>`}
function formatDate(v){if(!v)return'Unknown date';return new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function periodLabel(p){return p===1?'1H':'2H'}
function goalTimeLabel(e){return `${periodLabel(e.period)} ${e.minute}'${e.goalType==='penalty'?' PEN':''}`;}
function showView(view){Object.values(views).forEach(v=>v?.classList.add('hidden'));if(!view)return;view.classList.remove('hidden');view.classList.remove('screen-enter');void view.offsetWidth;view.classList.add('screen-enter');window.scrollTo({top:0,behavior:'auto'});if(view===views.homeView)renderHome();if(view===views.matchesView)renderMatchesView();if(view===views.statsView)renderStatsView();if(view===views.settingsView)renderSettings();}
function updatePlanRadios(){const plan='platinum';document.querySelectorAll('[name="planPreview"]').forEach(r=>{r.checked=plan===r.value});const status=$('planPreviewStatus');if(status)status.textContent=plan==='platinum'?'Previewing ⭐ Platinum':'Previewing Free'}
function applyCrestStyle(el,primary,secondary){if(!el)return;el.style.setProperty('--team-primary',primary||'#25df72');el.style.setProperty('--team-secondary',secondary||'#0b2a38');el.style.borderColor=primary||'#25df72';el.style.background=`linear-gradient(180deg,${secondary||'#0b2a38'},${primary||'#25df72'}33)`} function refreshIdentity(){const s=loadSettings(),t=teamDisplay();document.documentElement.style.setProperty('--club-primary',s.primaryColor||'#0c7a44');document.documentElement.style.setProperty('--club-secondary',s.secondaryColor||'#f4f3ec');for(const [id,val] of [['homeTeamCrest',t.abbr],['settingsTeamCrest',t.abbr],['onboardingTeamCrest',cleanAbbr($('onboardingTeamAbbr')?.value,t.abbr)]])if($(id))$(id).textContent=val;if($('homeTeamName'))$('homeTeamName').textContent=t.name;applyCrestStyle($('homeTeamCrest'),s.primaryColor,s.secondaryColor);applyCrestStyle($('settingsTeamCrest'),s.primaryColor,s.secondaryColor);applyCrestStyle($('onboardingTeamCrest'),s.onboardingPrimaryColor||s.primaryColor,s.onboardingSecondaryColor||s.secondaryColor)}
function renderSettings(){const s=loadSettings();if($('teamName'))$('teamName').value=s.teamName||'Your Team';if($('teamAbbr'))$('teamAbbr').value=cleanAbbr(s.teamAbbr,'YTM');if($('matchFormat'))$('matchFormat').value=String(s.matchFormat);if($('playersOnPitch'))$('playersOnPitch').value=s.playersOnPitch;if($('ageGroup'))$('ageGroup').value=s.ageGroup||'';if($('season'))$('season').value=s.season||'2026/27';if($('primaryColor'))$('primaryColor').value=s.primaryColor||'#25df72';if($('secondaryColor'))$('secondaryColor').value=s.secondaryColor||'#0b2a38';const sq=$('squadSize');if(sq?.closest('label'))sq.closest('label').style.display='none';updatePlanRadios();renderPlayers();refreshIdentity();renderTeamPreview()}
function renderPlayers(){const ps=loadPlayers();if($('squadCount'))$('squadCount').textContent=`${ps.length} players`;if(!$('playerList'))return;$('playerList').innerHTML=ps.length?`<div class="gs-settings-player-grid">${[...ps].sort((a,b)=>(Number(a.number)||999)-(Number(b.number)||999)).map(p=>`<button class="gs-settings-player" type="button" data-edit-player="${p.id}">${playerActionTile(p)}<span class="gsp-edit">Edit</span></button>`).join('')}</div>`:'<p class="muted">No players yet.</p>';document.querySelectorAll('[data-edit-player]').forEach(b=>b.onclick=()=>openEditPlayer(b.dataset.editPlayer));}
let editingPlayerId=null;
function openPlayerDialog(id=null){editingPlayerId=id;const p=id&&loadPlayers().find(x=>x.id===id);$('playerDialogTitle').textContent=p?'Edit player':'Add player';$('playerName').value=p?.name||'';$('playerNumber').value=p?.number||'';$('playerPosition').value=p?.position||'';$('deletePlayerBtn').classList.toggle('hidden',!p);$('playerDialog').showModal();$('playerName').focus()}
const openEditPlayer=id=>openPlayerDialog(id);
function renderHome(){refreshIdentity();renderSeasonSummary();renderMatchHistory();}
function renderSeasonSummary(){
 const matches=loadMatches().filter(m=>m.status==='completed'||m.fullTime);
 const premium=loadSettings().planPreview==='platinum';
 let wins=0,draws=0,losses=0,gf=0,ga=0;
 matches.forEach(m=>{gf+=m.ourScore||0;ga+=m.theirScore||0;if(m.ourScore>m.theirScore)wins++;else if(m.ourScore<m.theirScore)losses++;else draws++});
 $('seasonSummary').innerHTML=`<div class="stat-card"><strong>${matches.length}</strong><span>Matches recorded</span></div>`+(premium?`<div class="stat-card"><strong>${gf}</strong><span>Team goals</span></div><div class="stat-card"><strong>${wins}</strong><span>Wins</span></div>`:'');
 if(!matches.length){$('playerStatsTable').innerHTML='<p class="muted stats-empty">Complete a match and your football record will appear here.</p>';return}
 const stats=getPlayerStats('All'),top=[...stats.rows].filter(p=>p.goals>0).sort((a,b)=>b.goals-a.goals)[0];
 $('playerStatsTable').innerHTML=`<div class="home-season-snapshot">${top?`<div class="home-top-scorer"><span>${premium?'Season leader':'Top scorer'}</span><strong>${escapeHtml(top.name)} <em>⚽ ${top.goals}</em></strong></div>`:'<p class="muted">No goals recorded yet.</p>'}<button type="button" class="secondary-btn" id="homeStatsBtn">View season stats</button></div>`;
 $('homeStatsBtn')?.addEventListener('click',()=>showView(views.statsView));
}function renderPlayerCards(rows){$('playerStatsTable').innerHTML=`<div class="player-stats-list">${rows.map(p=>`<article class="player-stat-card"><button class="player-stat-head player-stat-toggle" type="button" aria-expanded="false"><div class="player-stat-shirt">${escapeHtml(p.number||'–')}</div><div class="player-stat-identity"><strong>${escapeHtml(p.name)}</strong>${p.position?`<span>${escapeHtml(p.position)}</span>`:''}</div><div class="player-stat-mini"><span><strong>${p.apps}</strong> Apps</span><span><strong>${p.starts}</strong> Starts</span><span class="mini-goal"><strong>${p.goals}</strong> Goals</span><span class="mini-assist"><strong>${p.assists}</strong> Assists</span></div><span class="player-stat-chevron">⌄</span></button><div class="player-stat-details" hidden><div class="player-stat-grid"><div><strong>${p.apps}</strong><span>Apps</span></div><div><strong>${p.starts}</strong><span>Starts</span></div><div><strong>${p.subApps}</strong><span>Subs</span></div><div><strong>${p.minutes}</strong><span>Minutes</span></div><div class="stat-accent-goal"><strong>${p.goals}</strong><span>Goals</span></div><div class="stat-accent-assist"><strong>${p.assists}</strong><span>Assists</span></div></div></div></article>`).join('')}</div>`;document.querySelectorAll('.player-stat-toggle').forEach(btn=>btn.onclick=()=>{const d=btn.closest('.player-stat-card').querySelector('.player-stat-details'),exp=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!exp));d.hidden=exp;btn.closest('.player-stat-card').classList.toggle('is-expanded',!exp)})}
function getPlayerStats(filter){const matches=loadMatches().filter(m=>(m.status==='completed'||m.fullTime)&& (filter==='All'||(m.competition||'League')===filter));const ps=loadPlayers();const out={};ps.forEach(p=>out[p.id]={id:p.id,name:p.name,number:p.number||'',position:p.position||'',apps:0,starts:0,subApps:0,minutes:0,goals:0,assists:0});for(const m of matches){const starters=new Set(m.starterPlayerIds||[]),participants=new Set(starters);for(const e of m.events||[]){if(e.type==='substitution'&&e.onId)participants.add(e.onId);if(e.type==='players_adjust_our'&&e.playerId)participants.add(e.playerId);if(e.type==='our_goal'&&e.playerId&&e.goalType!=='own_goal'&&out[e.playerId])out[e.playerId].goals++;if(e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal'&&out[e.assistPlayerId])out[e.assistPlayerId].assists++}participants.forEach(id=>{if(out[id]){out[id].apps++;if(starters.has(id))out[id].starts++;else out[id].subApps++}});const mins=computeMinutes(m);Object.entries(mins).forEach(([id,s])=>{if(out[id])out[id].minutes+=Math.round(s/60)})}return{rows:Object.values(out).sort((a,b)=>b.goals-a.goals||b.apps-a.apps||(Number(a.number)||999)-(Number(b.number)||999)),matches}}
function computeMinutes(match){const byPeriod={1:0,2:0};if(match.periodDurations){byPeriod[1]=match.periodDurations[1]||0;byPeriod[2]=match.periodDurations[2]||0}else{byPeriod[1]=match.halfTimeScore?((match.period===2?match.halfTimeElapsedSeconds:match.periodElapsedSeconds)||0):(match.periodElapsedSeconds||0);byPeriod[2]=match.period===2?match.periodElapsedSeconds||0:0}const totals={};const events=match.events||[];let active=new Set(match.starterPlayerIds||[]);let currentPeriod=1,last=0;const add=(ids,sec)=>ids.forEach(id=>totals[id]=(totals[id]||0)+Math.max(0,sec));for(const e of events){if(e.period!==currentPeriod){add(active,Math.max(0,byPeriod[currentPeriod]-last));currentPeriod=e.period;last=0}const t=Number(e.seconds??((e.minute||1)-1)*60);add(active,t-last);last=t;if(e.type==='substitution'){if(e.offId)active.delete(e.offId);if(e.onId)active.add(e.onId)}else if(e.type==='players_adjust_our'){if(e.direction==='on')active.add(e.playerId);else active.delete(e.playerId)}}add(active,Math.max(0,byPeriod[currentPeriod]-last));return totals}
function renderMatchHistory(){const matches=loadMatches().filter(m=>m.status==='completed'||m.fullTime).sort((a,b)=>(b.completedAt||b.createdAt||'').localeCompare(a.completedAt||a.createdAt||''));$('matchHistoryList').innerHTML=matches.length?matches.slice(0,6).map(m=>{const r=m.ourScore>m.theirScore?'W':m.ourScore<m.theirScore?'L':'D';return`<button class="history-card premium-result-row" type="button" data-history-match="${m.id}"><span class="result-pill result-${r.toLowerCase()}">${r}</span><span class="history-main"><span class="history-opponent">${escapeHtml(m.teamAbbr||teamDisplay().abbr)} <strong>${m.ourScore}-${m.theirScore}</strong> ${escapeHtml(m.opponentAbbr||derivedAbbr(m.opponent))}</span><br><span class="history-result">${m.competition||'League'} · ${escapeHtml(m.opponent)}</span></span><span class="history-date">${formatDate(m.date)}</span></button>`}).join(''):'<p class="muted">No completed matches yet.</p>';document.querySelectorAll('[data-history-match]').forEach(b=>b.onclick=()=>openMatchReport(b.dataset.historyMatch))}
function renderMatchesView(){const fx=loadFixtures();$('upcomingMatchesList').innerHTML=fx.length?fx.map(f=>`<div class="history-card"><span class="history-date">${formatDate(f.date)}</span><span class="history-main"><span class="history-opponent">${escapeHtml(teamDisplay().name)} vs ${escapeHtml(f.opponent)}</span><br><span class="history-result">${f.competition||'League'} · ${f.venue==='away'?'Away':'Home'}</span></span></div>`).join(''):'<p class="muted">No upcoming fixtures.</p>';$('matchesResultsList').innerHTML=$('matchHistoryList').innerHTML;document.querySelectorAll('#matchesResultsList [data-history-match]').forEach(b=>b.onclick=()=>openMatchReport(b.dataset.historyMatch))}
let statsDisplayMode='cards',statsSection='overview';
function buildMoments(filter='All'){
 const matches=loadMatches().filter(m=>(m.status==='completed'||m.fullTime)&&(filter==='All'||(m.competition||'League')===filter)).sort((a,b)=>(a.date||'').localeCompare(b.date||''));
 const players=Object.fromEntries(loadPlayers().map(p=>[p.id,p])),moments=[],seenGoal=new Set(),seenAssist=new Set(),seenApp=new Set();let firstWin=false;
 for(const m of matches){
  const participants=new Set(m.starterPlayerIds||[]);
  (m.events||[]).forEach(e=>{if(e.type==='substitution'&&e.onId)participants.add(e.onId);if(e.type==='players_adjust_our'&&e.playerId&&e.direction==='on')participants.add(e.playerId)});
  participants.forEach(id=>{if(!seenApp.has(id)&&players[id]){seenApp.add(id);moments.push({icon:'⭐',title:'First Appearance',who:players[id].name,detail:`Made their first recorded appearance vs ${m.opponent||'the opposition'}`,date:m.date})}});
  if(!firstWin&&(m.ourScore||0)>(m.theirScore||0)){firstWin=true;moments.push({icon:'🏆',title:'First Win',who:teamDisplay().name,detail:`First recorded win: ${m.ourScore}-${m.theirScore} vs ${m.opponent||'the opposition'}`,date:m.date})}
  const goalsByPlayer={};
  for(const e of m.events||[]){
   if(e.type==='our_goal'&&e.playerId&&e.goalType!=='own_goal'&&players[e.playerId]){
    goalsByPlayer[e.playerId]=(goalsByPlayer[e.playerId]||0)+1;
    if(!seenGoal.has(e.playerId)){seenGoal.add(e.playerId);moments.push({icon:'⚽',title:'First Goal',who:players[e.playerId].name,detail:`Scored their first recorded goal vs ${m.opponent||'the opposition'}`,date:m.date})}
   }
   if(e.type==='our_goal'&&e.assistPlayerId&&players[e.assistPlayerId]&&!seenAssist.has(e.assistPlayerId)){seenAssist.add(e.assistPlayerId);moments.push({icon:'🎯',title:'First Assist',who:players[e.assistPlayerId].name,detail:`Recorded their first assist vs ${m.opponent||'the opposition'}`,date:m.date})}
  }
  Object.entries(goalsByPlayer).forEach(([id,n])=>{if(n>=3)moments.push({icon:'🎩',title:n===3?'Hat-trick':`${n}-Goal Match`,who:players[id].name,detail:`Scored ${n} goals vs ${m.opponent||'the opposition'}`,date:m.date})});
 }
 const stats=getPlayerStats(filter),team=getTeamStats(filter);
 stats.rows.forEach(p=>{
  [10,20,25,50,100].forEach(n=>{if(p.apps>=n)moments.push({icon:'👕',title:`${n} Appearances`,who:p.name,detail:`Reached ${n} appearances`,date:''})});
  [10,20,25,50].forEach(n=>{if(p.goals>=n)moments.push({icon:'⚽',title:`${n} Season Goals`,who:p.name,detail:`Reached ${n} goals`,date:''})});
  [10,20,25].forEach(n=>{if(p.assists>=n)moments.push({icon:'🎯',title:`${n} Assists`,who:p.name,detail:`Reached ${n} assists`,date:''})});
 });
 [5,10,20,25,50].forEach(n=>{if(team.won>=n)moments.push({icon:'🏆',title:`${n} Team Wins`,who:teamDisplay().name,detail:`Reached ${n} wins`,date:''})});
 [25,50,100].forEach(n=>{if(team.gf>=n)moments.push({icon:'⚽',title:`${n} Team Goals`,who:teamDisplay().name,detail:`Reached ${n} goals`,date:''})});
 return moments.reverse();
}
function renderStatsView(){
 const premium=loadSettings().planPreview==='platinum',stats=getPlayerStats(statsFilter),team=getTeamStats(statsFilter);
 if(!premium){
  $('statsViewBody').innerHTML=`<div class="free-stats-card"><h3>${stats.matches.length} matches recorded</h3>${stats.rows.filter(p=>p.goals>0).map(p=>`<div class="free-goal-row"><strong>${escapeHtml(p.name)}</strong><span>⚽ ${p.goals}</span></div>`).join('')||'<p class="muted">No goals recorded yet.</p>'}<div class="upgrade-preview"><strong>🔒 Full statistics are a Platinum feature</strong><span>Team results · player appearances · minutes · assists · competition filters · memorable moments</span><button class="primary-btn" id="statsUpgradeInline" type="button">Explore Platinum</button></div></div>`;
  $('statsUpgradeInline')?.addEventListener('click',()=>showView(views.platinumView));return;
 }
 const st=loadSettings(),tabs=`<div class="platinum-stats-tabs"><button data-statsection="overview" class="${statsSection==='overview'?'active':''}">Overview</button><button data-statsection="players" class="${statsSection==='players'?'active':''}">Players</button><button data-statsection="moments" class="${statsSection==='moments'?'active':''}">Moments</button></div>`;
 let body='';
 if(statsSection==='overview'){
  body=`<div class="stat-cards"><div class="stat-card"><strong>${team.played}</strong><span>Played</span></div><div class="stat-card"><strong>${team.won}</strong><span>Won</span></div><div class="stat-card"><strong>${team.drawn}</strong><span>Drawn</span></div><div class="stat-card"><strong>${team.lost}</strong><span>Lost</span></div><div class="stat-card"><strong>${team.gf}</strong><span>Goals For</span></div><div class="stat-card"><strong>${team.ga}</strong><span>Against</span></div></div><div class="insight-panel"><strong>Season story</strong><span>${team.played?`${team.won} wins from ${team.played} matches · ${team.gf} goals scored.`:'Your season story will build as matches are completed.'}</span></div>`;
 }else if(statsSection==='players'){
  const toggle=`<div class="stats-display-toggle"><button type="button" data-statmode="cards" aria-pressed="${statsDisplayMode==='cards'}" class="${statsDisplayMode==='cards'?'active':''}">Cards</button><button type="button" data-statmode="table" aria-pressed="${statsDisplayMode==='table'}" class="${statsDisplayMode==='table'?'active':''}">Table</button></div>`;
  const cards=`<div class="player-card-carousel gs-v3-carousel">${stats.rows.map(p=>`<article class="gs-player-card-v3 stats-version" style="${cardStyle()}"><div class="gsc-club">${escapeHtml(st.teamName||'Your Club')}</div><div class="gsc-abbr">${escapeHtml(cleanAbbr(st.teamAbbr,'TEAM'))}</div><div class="gsc-name">${escapeHtml(p.name.toUpperCase())}</div><div class="gsc-number">${escapeHtml(p.number||'–')}</div><div class="gsc-position">${escapeHtml((p.position||'Player').toUpperCase())}</div><div class="gsc-sign">${escapeHtml(p.name)}</div><div class="gsc-stats"><span><b>${p.goals}</b>Goals</span><span><b>${p.assists}</b>Assists</span><span><b>${p.apps}</b>Apps</span></div></article>`).join('')}</div>`;
  const table=`<div class="stats-table-scroll"><table class="premium-stats-table"><thead><tr><th>Player</th><th>Apps</th><th>Starts</th><th>Goals</th><th>Assists</th><th>Minutes</th></tr></thead><tbody>${stats.rows.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${p.apps}</td><td>${p.starts}</td><td>${p.goals}</td><td>${p.assists}</td><td>${p.minutes}</td></tr>`).join('')}</tbody></table></div>`;
  body=toggle+(statsDisplayMode==='cards'?cards:table);
 }else{
  const moments=buildMoments(statsFilter);
  body=`<div class="moments-intro"><strong>Your GrassStatory</strong><span>Milestones and memorable moments created from the season you've recorded.</span></div><div class="moments-list">${moments.length?moments.map((m,i)=>`<article class="moment-card"><div class="moment-icon">${m.icon}</div><div><p class="eyebrow">MEMORABLE MOMENT</p><h3>${escapeHtml(m.title)}</h3><strong>${escapeHtml(m.who)}</strong><p>${escapeHtml(m.detail)}</p>${m.date?`<small>${formatDate(m.date)}</small>`:''}</div><button type="button" class="secondary-btn moment-share" data-moment="${i}">Share</button></article>`).join(''):`<div class="empty-moments"><strong>Your memorable moments will appear here.</strong><span>Appearances, goals, assists and team milestones are tracked automatically as your season grows.</span></div>`}</div>`;
 }
 $('statsViewBody').innerHTML=tabs+body;
 document.querySelectorAll('[data-statsection]').forEach(b=>b.onclick=()=>{statsSection=b.dataset.statsection;renderStatsView()});
 document.querySelectorAll('[data-statmode]').forEach(b=>b.onclick=()=>{statsDisplayMode=b.dataset.statmode;renderStatsView()});
 document.querySelectorAll('.moment-share').forEach(b=>b.onclick=()=>alert('Shareable Moment cards will use the GrassStatory share-card generator.'));
}function getTeamStats(filter){const ms=loadMatches().filter(m=>(m.status==='completed'||m.fullTime)&&(filter==='All'||(m.competition||'League')===filter));let won=0,drawn=0,lost=0,gf=0,ga=0;ms.forEach(m=>{gf+=m.ourScore||0;ga+=m.theirScore||0;if(m.ourScore>m.theirScore)won++;else if(m.ourScore<m.theirScore)lost++;else drawn++});return{played:ms.length,won,drawn,lost,gf,ga}}
function setMatchWizardStep(step){document.querySelectorAll('.match-wizard-step').forEach(s=>s.classList.toggle('hidden',Number(s.dataset.matchStep)!==step));const title=$('matchLobbyTitle');if(title)title.textContent=step===1?'New Match':step===2?'Match Details':step===3?'Match Squad':'Starting Team';window.scrollTo({top:0,behavior:'auto'});}
function openMatchSetup(){const ps=loadPlayers(),s=loadSettings();if(ps.length<s.playersOnPitch){alert(`Add at least ${s.playersOnPitch} players first.`);return}window._available=new Set(ps.map(p=>p.id));window._starters=new Set(lastStartingIds());$('matchDate').value=new Date().toISOString().slice(0,10);$('opponentName').value='';$('opponentAbbr').value='';if($('matchCompetition'))$('matchCompetition').value='League';$('matchSetupError').textContent='';renderMatchSelection();showView(views.matchSetupView);setMatchWizardStep(1);renderMilestoneWatch()}
function lastStartingIds(){const ps=new Set(loadPlayers().map(p=>p.id));const last=loadMatches().filter(m=>m.status==='completed'||m.fullTime).sort((a,b)=>(b.completedAt||b.createdAt||'').localeCompare(a.completedAt||a.createdAt||''))[0];const ids=(last?.starterPlayerIds||[]).filter(id=>ps.has(id));const n=loadSettings().playersOnPitch;return ids.length===n?ids:loadPlayers().slice(0,n).map(p=>p.id)}
function renderMatchSelection(){const ps=loadPlayers(),s=loadSettings();$('lobbyFormatText').textContent=`${s.matchFormat}v${s.matchFormat}`;$('startingTeamHeading').textContent=`Starting ${s.playersOnPitch}`;$('availableCount').textContent=`${window._available.size} available`;$('starterCount').textContent=`${window._starters.size} / ${s.playersOnPitch}`;$('availabilityList').innerHTML=`<div class="gs-selection-grid">${ps.map(p=>`<label class="gs-select-wrap"><input type="checkbox" class="availability-check" data-id="${p.id}" ${window._available.has(p.id)?'checked':''}>${playerActionTile(p,window._available.has(p.id))}</label>`).join('')}</div>`;$('starterList').innerHTML=`<div class="gs-selection-grid">${ps.filter(p=>window._available.has(p.id)).map(p=>`<label class="gs-select-wrap"><input type="checkbox" class="starter-check" data-id="${p.id}" ${window._starters.has(p.id)?'checked':''}>${playerActionTile(p,window._starters.has(p.id))}</label>`).join('')}</div>`;$('substituteList').innerHTML=`<div class="gs-bench-grid">${ps.filter(p=>window._available.has(p.id)&&!window._starters.has(p.id)).map(p=>playerActionTile(p,false)).join('')}</div>`||'<p class="muted">No substitutes selected.</p>';document.querySelectorAll('.availability-check').forEach(c=>c.onchange=()=>{if(c.checked)window._available.add(c.dataset.id);else{window._available.delete(c.dataset.id);window._starters.delete(c.dataset.id)}renderMatchSelection()});document.querySelectorAll('.starter-check').forEach(c=>c.onchange=()=>{if(c.checked){if(window._starters.size>=s.playersOnPitch){c.checked=false;return}window._starters.add(c.dataset.id)}else window._starters.delete(c.dataset.id);renderMatchSelection()})}
function currentMatch(){return loadMatches().find(m=>m.id===activeMatchId)||null}
function saveCurrent(m){const ms=loadMatches(),i=ms.findIndex(x=>x.id===m.id);if(i>=0){ms[i]=m;saveMatches(ms)}}
function ensureMatch(m){if(!Array.isArray(m.events))m.events=[];if(!Array.isArray(m.currentOnPitch))m.currentOnPitch=[...(m.starterPlayerIds||[])];if(!Array.isArray(m.currentSubs))m.currentSubs=[...(m.substitutePlayerIds||[])];if(!m.period)m.period=1;if(typeof m.halfTime!=='boolean')m.halfTime=false;if(typeof m.fullTime!=='boolean')m.fullTime=m.status==='completed';if(typeof m.periodElapsedSeconds!=='number')m.periodElapsedSeconds=0;if(!m.periodDurations)m.periodDurations={};if(typeof m.opponentPlayersOnPitch!=='number')m.opponentPlayersOnPitch=loadSettings().playersOnPitch;if(!m.competition)m.competition='League';return m}
function openLive(id){activeMatchId=id;const m=ensureMatch(currentMatch());m.periodStartedAt=null;saveCurrent(m);renderLive();showView(views.liveMatchView)}
function elapsedNow(){const m=currentMatch();if(!m)return 0;return(m.periodElapsedSeconds||0)+(m.periodStartedAt?Math.floor((Date.now()-m.periodStartedAt)/1000):0)}
function matchMinute(){return Math.floor(elapsedNow()/60)+1}
function updateClock(){const m=currentMatch();if(!$('matchClock')||!m)return;$('matchClock').textContent=`${String(Math.floor(elapsedNow()/60)).padStart(2,'0')}:${String(elapsedNow()%60).padStart(2,'0')}`;$('clockStatus').textContent=m.periodStartedAt?'Running':'Paused'}
function startTimer(){const m=currentMatch();if(!m||m.fullTime||m.halfTime||m.periodStartedAt)return;m.periodStartedAt=Date.now();saveCurrent(m);stopTimer();timerInterval=setInterval(updateClock,250);renderLive()}
function pauseTimer(){const m=currentMatch();if(!m||!m.periodStartedAt)return;m.periodElapsedSeconds=elapsedNow();m.periodStartedAt=null;saveCurrent(m);stopTimer();updateClock()}
function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}}
function renderLive(){const m=ensureMatch(currentMatch());if(!m)return;const t=teamDisplay();$('ourScore').textContent=m.ourScore;$('theirScore').textContent=m.theirScore;$('ourTeamName').textContent=m.teamName||t.name;$('ourTeamCrest').textContent=cleanAbbr(m.teamAbbr,t.abbr);$('opponentScoreName').textContent=m.opponent;$('opponentTeamCrest').textContent=cleanAbbr(m.opponentAbbr,derivedAbbr(m.opponent));$('liveMeta').textContent=`${m.opponent} · ${m.venue==='home'?'Home':'Away'} · ${m.competition}`;$('livePlayerCount').textContent=`${m.currentOnPitch.length}v${m.opponentPlayersOnPitch}`;$('matchPeriod').textContent=m.period===1?'1st half':'2nd half';$('periodLabel').textContent=m.fullTime?'Full Time':(m.halfTime?'Half Time':(m.period===1?'1st Half':'2nd Half'));$('timerBtn').textContent=m.periodStartedAt?'Pause':'Start';$('timerBtn').disabled=m.fullTime||m.halfTime;$('halfTimeBtn').classList.toggle('hidden',m.period!==1||m.halfTime||m.fullTime);$('startSecondHalfBtn').classList.toggle('hidden',!(m.period===1&&m.halfTime&&!m.fullTime));$('fullTimeBtn').classList.toggle('hidden',!(m.period===2&&!m.fullTime));$('liveStarters').innerHTML=renderOurOnPitch(m);$('liveSubs').innerHTML=renderOurSubs(m);$('playersOnPitchStatus').textContent=`${m.currentOnPitch.length} v ${m.opponentPlayersOnPitch} · both sides can be adjusted.`;$('eventTimeline').innerHTML=m.events.length?[...m.events].reverse().map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join(''):'<p class="muted">No events yet.</p>';$('undoBtn').disabled=!m.events.length;updateClock();saveCurrent(m)}
function renderOurOnPitch(m){const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));const arr=m.currentOnPitch.map(id=>by[id]).filter(Boolean);return arr.length?`<div class="gs-live-player-grid">${arr.map(p=>playerActionTile(p)).join('')}</div>`:'<p class="muted">No players on pitch.</p>'}
function renderOurSubs(m){const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));const arr=m.currentSubs.map(id=>by[id]).filter(Boolean);return arr.length?`<div class="gs-live-player-grid">${arr.map(p=>playerActionTile(p)).join('')}</div>`:'<p class="muted">No substitutes.</p>'}
function eventText(e){const m=currentMatch(); const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));if(e.type==='our_goal'){const gt=e.goalType==='penalty'?' (Penalty)':e.goalType==='own_goal'?' (Opposition Own Goal)':'';return`⚽ ${e.playerId&&by[e.playerId]?playerLabel(by[e.playerId]):'Opposition Own Goal'}${e.assistPlayerId&&by[e.assistPlayerId]?` — Assist: ${playerLabel(by[e.assistPlayerId])}`:''}${gt}`}if(e.type==='their_goal'){const gt=e.goalType==='penalty'?' (Penalty)':e.goalType==='own_goal'?' (Our Own Goal)':'';return`⚽ ${e.ownGoalPlayerId&&by[e.ownGoalPlayerId]?`${playerLabel(by[e.ownGoalPlayerId])} own goal`:m?.opponent||'Opponent'}${gt}`}if(e.type==='substitution')return`🔄 ${by[e.offId]?playerLabel(by[e.offId]):'Unknown'} off → ${by[e.onId]?playerLabel(by[e.onId]):'Unknown'} on`;if(e.type==='players_adjust_our')return`👥 ${by[e.playerId]?playerLabel(by[e.playerId]):'Player'} ${e.direction==='on'?'on':'off'} · ${e.newCount} on pitch`;if(e.type==='players_adjust_opponent')return`👥 Opponent now ${e.newCount} on pitch`;return e.type}
function eventState(m){return{currentOnPitch:[...(m.currentOnPitch||[])],currentSubs:[...(m.currentSubs||[])],opponentPlayersOnPitch:Number(m.opponentPlayersOnPitch)}}
function restoreState(m,s){m.currentOnPitch=[...(s.currentOnPitch||[])];m.currentSubs=[...(s.currentSubs||[])];m.opponentPlayersOnPitch=Number(s.opponentPlayersOnPitch)||loadSettings().playersOnPitch}
function recordGoal(kind,goalType,playerId,assistId,ownGoalPlayerId){const m=ensureMatch(currentMatch());if(!m||m.halfTime||m.fullTime)return;m.periodElapsedSeconds=elapsedNow();if(m.periodStartedAt)m.periodStartedAt=Date.now();const e={id:makeId(),type:kind,period:m.period,seconds:elapsedNow(),minute:matchMinute(),goalType,playerId:playerId||null,assistPlayerId:assistId||null,ownGoalPlayerId:ownGoalPlayerId||null,beforeScore:{our:m.ourScore,their:m.theirScore},beforeState:eventState(m)};m.events.push(e);if(kind==='our_goal')m.ourScore++;else m.theirScore++;saveCurrent(m);renderLive()}
function openGoalDialog(kind){const m=ensureMatch(currentMatch());if(!m||m.halfTime||m.fullTime)return;const our=kind==='our_goal';$('goalDialogTitle').textContent=our?'Our Goal':'Opponent Goal';$('goalPlayerSection').classList.toggle('hidden',!our);$('goalType').value='normal';$('goalScorer').disabled=false;$('goalAssist').disabled=false;$('ownGoalPlayer').disabled=false;$('ownGoalPlayerWrap').classList.add('hidden');$('goalAssist').value='';$('ownGoalPlayer').value='';$('goalPlayerSection').querySelectorAll('select').forEach(x=>x.disabled=false);const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));if(our){const on=m.currentOnPitch.map(id=>by[id]).filter(Boolean);$('goalScorer').innerHTML=on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('');$('goalAssist').innerHTML='<option value="">No Assist</option>'+on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('');$('ownGoalPlayer').innerHTML='<option value="">Not specified</option>'+on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('')}else{$('ownGoalPlayer').innerHTML='<option value="">Not specified</option>'+m.currentOnPitch.map(id=>by[id]).filter(Boolean).map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('')}$('goalDialog').dataset.kind=kind;$('goalDialog').showModal()}
function openSubDialog(){const m=currentMatch();if(!m||m.halfTime||m.fullTime)return;if(!m.currentSubs.length){alert('There are no substitutes available.');return}batchOffIds=new Set();batchOnIds=new Set();renderBatchSubs();$('subDialog').showModal()}
function renderBatchSubs(){const m=currentMatch(),by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));$('subOffList').innerHTML=m.currentOnPitch.map(id=>by[id]).filter(Boolean).map(p=>`<label class="batch-choice"><input type="checkbox" class="batch-off-check" data-id="${p.id}" ${batchOffIds.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('subOnList').innerHTML=m.currentSubs.map(id=>by[id]).filter(Boolean).map(p=>`<label class="batch-choice"><input type="checkbox" class="batch-on-check" data-id="${p.id}" ${batchOnIds.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('subOffCount').textContent=batchOffIds.size;$('subOnCount').textContent=batchOnIds.size;const valid=batchOffIds.size>0&&batchOffIds.size===batchOnIds.size;$('saveBatchSubsBtn').disabled=!valid;$('saveBatchSubsBtn').textContent=valid?`Save ${batchOffIds.size} substitution${batchOffIds.size===1?'':'s'}`:'Save substitutions';document.querySelectorAll('.batch-off-check').forEach(c=>c.onchange=()=>{c.checked?batchOffIds.add(c.dataset.id):batchOffIds.delete(c.dataset.id);renderBatchSubs()});document.querySelectorAll('.batch-on-check').forEach(c=>c.onchange=()=>{c.checked?batchOnIds.add(c.dataset.id):batchOnIds.delete(c.dataset.id);renderBatchSubs()})}
function saveBatchSubs(){const m=currentMatch();if(!m||!batchOffIds.size||batchOffIds.size!==batchOnIds.size)return;const before=eventState(m),offs=[...batchOffIds],ons=[...batchOnIds],sec=elapsedNow(),min=matchMinute();offs.forEach((off,i)=>{const on=ons[i];const ev={id:makeId(),type:'substitution',period:m.period,seconds:sec,minute:min,offId:off,onId:on,beforeState:eventState(m)};m.currentOnPitch=m.currentOnPitch.filter(id=>id!==off);m.currentOnPitch.push(on);m.currentSubs=m.currentSubs.filter(id=>id!==on);m.currentSubs.push(off);m.events.push(ev)});saveCurrent(m);$('subDialog').close();renderLive()}
function openAdjust(){const m=currentMatch();if(!m||m.halfTime||m.fullTime)return;adjustOurIds=new Set(m.currentOnPitch);adjustOpponentCount=m.opponentPlayersOnPitch;renderAdjust();$('adjustPlayersDialog').showModal()}
function renderAdjust(){const m=currentMatch(),by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));$('adjustOurTeamName').textContent=m.teamName||teamDisplay().name;$('adjustOpponentName').textContent=m.opponent;$('adjustOurCount').textContent=adjustOurIds.size;$('adjustOpponentCount').textContent=adjustOpponentCount;$('oppCountValue').textContent=adjustOpponentCount;$('adjustOurOnList').innerHTML=loadPlayers().filter(p=>adjustOurIds.has(p.id)).map(p=>`<label class="adjust-choice"><input type="checkbox" class="adjust-on" data-id="${p.id}" checked><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('adjustOurOffList').innerHTML=loadPlayers().filter(p=>!adjustOurIds.has(p.id)).map(p=>`<label class="adjust-choice"><input type="checkbox" class="adjust-off" data-id="${p.id}"><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');document.querySelectorAll('.adjust-on').forEach(c=>c.onchange=()=>{if(!c.checked)adjustOurIds.delete(c.dataset.id);renderAdjust()});document.querySelectorAll('.adjust-off').forEach(c=>c.onchange=()=>{if(c.checked)adjustOurIds.add(c.dataset.id);renderAdjust()});$('adjustPlayersHint').textContent=`Current match state: ${adjustOurIds.size} v ${adjustOpponentCount}.`}
function saveAdjust(){const m=currentMatch();if(!m)return;const before=eventState(m),sec=elapsedNow(),min=matchMinute(),old=new Set(m.currentOnPitch),next=new Set(adjustOurIds);for(const id of next)if(!old.has(id))m.events.push({id:makeId(),type:'players_adjust_our',period:m.period,seconds:sec,minute:min,playerId:id,direction:'on',newCount:next.size,beforeState:before});for(const id of old)if(!next.has(id))m.events.push({id:makeId(),type:'players_adjust_our',period:m.period,seconds:sec,minute:min,playerId:id,direction:'off',newCount:next.size,beforeState:before});if(m.opponentPlayersOnPitch!==adjustOpponentCount)m.events.push({id:makeId(),type:'players_adjust_opponent',period:m.period,seconds:sec,minute:min,newCount:adjustOpponentCount,beforeState:before});m.currentOnPitch=[...next];m.currentSubs=loadPlayers().map(p=>p.id).filter(id=>m.availablePlayerIds.includes(id)&&!next.has(id));m.opponentPlayersOnPitch=adjustOpponentCount;saveCurrent(m);$('adjustPlayersDialog').close();renderLive()}
function goalTypeChanged(){const type=$('goalType').value;$('ownGoalPlayerWrap').classList.toggle('hidden',type!=='own_goal');$('goalPlayerSection').querySelectorAll('select').forEach(x=>x.disabled=type==='own_goal')}
function undoLast(){const m=currentMatch();if(!m?.events.length)return;const e=m.events.pop();if(e.beforeState)restoreState(m,e.beforeState);if(e.beforeScore){m.ourScore=e.beforeScore.our;m.theirScore=e.beforeScore.their}saveCurrent(m);renderLive()}
function halfTime(){const m=currentMatch();if(!m||m.period!==1||m.fullTime)return;pauseTimer();m.halfTime=true;m.periodDurations[1]=m.periodElapsedSeconds;m.halfTimeElapsedSeconds=m.periodElapsedSeconds;m.halfTimeScore={our:m.ourScore,their:m.theirScore};saveCurrent(m);renderLive()}
function startSecond(){const m=currentMatch();if(!m||!m.halfTime||m.fullTime)return;m.period=2;m.halfTime=false;m.periodElapsedSeconds=0;m.periodStartedAt=null;saveCurrent(m);renderLive();startTimer()}
function fullTime(){const m=currentMatch();if(!m||m.period!==2||m.fullTime)return;pauseTimer();m.periodDurations[2]=m.periodElapsedSeconds;m.fullTime=true;m.status='completed';m.finalScore={our:m.ourScore,their:m.theirScore};m.completedAt=new Date().toISOString();saveCurrent(m);openMatchReport(m.id)}
function openMatchReport(id){const m=loadMatches().find(x=>x.id===id);if(!m)return;window._report=m;currentMatchReport=m;$('reportOurName').textContent=m.teamName||teamDisplay().name;$('reportOpponent').textContent=m.opponent;$('reportOurCrest').textContent=cleanAbbr(m.teamAbbr,teamDisplay().abbr);$('reportOpponentCrest').textContent=cleanAbbr(m.opponentAbbr,derivedAbbr(m.opponent));$('reportMeta').textContent=`${formatDate(m.date)} · ${m.venue==='home'?'Home':'Away'}`;$('reportCompetition').textContent=m.competition||'League';$('reportOurScore').textContent=m.ourScore;$('reportTheirScore').textContent=m.theirScore;$('reportHalfScore').textContent=`${m.halfTimeScore?.our??0} - ${m.halfTimeScore?.their??0}`;const goals=(m.events||[]).filter(e=>e.type==='our_goal'||e.type==='their_goal');const premium=loadSettings().planPreview==='platinum';$('reportOurScorers').innerHTML=scorerSummary(m,'our_goal',premium);$('reportTheirScorers').innerHTML=scorerSummary(m,'their_goal',premium);const assists=goals.filter(e=>e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal').map(e=>{const p=loadPlayers().find(x=>x.id===e.assistPlayerId);return p?`${p.name} (${periodLabel(e.period)} ${e.minute}')`:''}).filter(Boolean);$('reportAssistSummary').classList.toggle('hidden',!assists.length);if(assists.length)$('reportAssistSummary').innerHTML=`<strong>Assists</strong> · ${escapeHtml(assists.join(', '))}`;$('reportGoals').innerHTML=goals.map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join('')||'<p class="muted">No goals recorded.</p>';const other=(m.events||[]).filter(e=>e.type==='substitution'||e.type==='players_adjust_our'||e.type==='players_adjust_opponent');$('reportSubs').innerHTML=other.map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join('')||'<p class="muted">No player changes recorded.</p>';$('reportStarters').innerHTML=(m.starterPlayerIds||[]).map(id=>loadPlayers().find(p=>p.id===id)).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No starters recorded.</p>';$('reportSubstitutes').innerHTML=(m.substitutePlayerIds||[]).map(id=>loadPlayers().find(p=>p.id===id)).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No substitutes recorded.</p>';const premiumReport=loadSettings().planPreview==='platinum';$('toggleMatchDetailsBtn').classList.toggle('hidden',!premiumReport);$('reportDetailsPanel').classList.toggle('hidden',!premiumReport);$('reportAssistSummary').classList.toggle('hidden',!premiumReport||!assists.length);renderReportMilestones(m);showView(views.matchReportView)}
let currentMatchReport=null;
function scorerSummary(m,type,premium=false){
  const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));
  const events=(m.events||[]).filter(e=>e.type===type);
  const groups=[];
  for(const e of events){
    if(e.goalType==='own_goal'){
      const label=type==='our_goal'?'Opposition Own Goal':(e.ownGoalPlayerId&&by[e.ownGoalPlayerId]?`${playerLabel(by[e.ownGoalPlayerId])} own goal`:'Our Own Goal');
      groups.push({name:label,times:[goalTimeLabel(e)]});
      continue;
    }
    const key=type==='their_goal'?'opp':e.playerId;
    let g=groups.find(x=>x.key===key);
    if(!g){g={key,name:type==='their_goal'?m.opponent:(by[e.playerId]?.name||'Unknown'),times:[]};groups.push(g)}
    g.times.push(goalTimeLabel(e));
  }
  return groups.map(g=>`<div class="scorer-group"><strong>${escapeHtml(g.name)}</strong><span>${premium?escapeHtml(g.times.join(' · ')):''}</span></div>`).join('')||'<span class="muted">No goals</span>';
}

function renderMilestoneWatch(){
  const panel=$('milestoneWatchPanel'),list=$('milestoneWatchList');
  if(!panel||!list)return;
  const premium=loadSettings().planPreview==='platinum';
  if(!premium){panel.classList.add('hidden');return}
  const ps=loadPlayers(), available=window._available||new Set(ps.map(p=>p.id)), starters=window._starters||new Set();
  const matches=loadMatches().filter(m=>m.status==='completed'||m.fullTime);
  const goals={}; const apps={}; const assists={};
  ps.forEach(p=>{goals[p.id]=0;apps[p.id]=0;assists[p.id]=0});
  for(const m of matches){
    const participants=new Set(m.starterPlayerIds||[]);
    for(const e of m.events||[]){
      if(e.type==='substitution'&&e.onId)participants.add(e.onId);
      if(e.type==='players_adjust_our'&&e.playerId)participants.add(e.playerId);
      if(e.type==='our_goal'&&e.playerId&&e.goalType!=='own_goal'&&goals[e.playerId]!=null)goals[e.playerId]++;
      if(e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal'&&assists[e.assistPlayerId]!=null)assists[e.assistPlayerId]++;
    }
    participants.forEach(id=>{if(apps[id]!=null)apps[id]++});
  }
  const items=[];
  for(const p of ps){
    if(!available.has(p.id))continue;
    if(starters.has(p.id)){
      const next=apps[p.id]+1;
      if(next%10===0)items.push({text:`${p.name} will make their ${next}th appearance if they play today.`,rank:3});
    }else if(apps[p.id]+1===10){items.push({text:`${p.name} will make their 10th appearance if they play today.`,rank:2})}
    if(goals[p.id]>=0 && [10,20,25,50].includes(goals[p.id]+1))items.push({text:`${p.name}'s next goal will be their ${goals[p.id]+1}th goal of the season.`,rank:4});
    if(assists[p.id]>=0 && [10,20,25,50].includes(assists[p.id]+1))items.push({text:`${p.name}'s next assist will be their ${assists[p.id]+1}th of the season.`,rank:2});
  }
  items.sort((a,b)=>b.rank-a.rank);
  const chosen=items.slice(0,5);
  if(!chosen.length){panel.classList.remove('hidden');list.innerHTML='<p class="muted compact">No major milestones are close enough to show today.</p>';return}
  panel.classList.remove('hidden');
  list.innerHTML=chosen.map(x=>`<div class="milestone-row">${escapeHtml(x.text)}</div>`).join('');
}
function renderReportMilestones(m){
  const box=$('reportMilestones'); if(!box)return;
  const premium=loadSettings().planPreview==='platinum'; if(!premium){box.classList.add('hidden');return}
  const ps=loadPlayers(), reached=[];
  const counts={}; ps.forEach(p=>counts[p.id]={g:0,a:0,app:0});
  for(const mm of loadMatches().filter(x=>x.status==='completed'||x.fullTime)){
    const part=new Set(mm.starterPlayerIds||[]);
    for(const e of mm.events||[]){
      if(e.type==='substitution'&&e.onId)part.add(e.onId);
      if(e.type==='players_adjust_our'&&e.playerId)part.add(e.playerId);
      if(e.type==='our_goal'&&e.playerId&&e.goalType!=='own_goal'&&counts[e.playerId])counts[e.playerId].g++;
      if(e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal'&&counts[e.assistPlayerId])counts[e.assistPlayerId].a++;
    }
    part.forEach(id=>{if(counts[id])counts[id].app++});
  }
  for(const p of ps){
    const c=counts[p.id]; if(!c)continue;
    if([10,20,25,50].includes(c.g))reached.push(`⚽ ${p.name} has reached ${c.g} season goals.`);
    if([10,20,25,50].includes(c.a))reached.push(`🎯 ${p.name} has reached ${c.a} assists.`);
    if([10,20,25,50].includes(c.app))reached.push(`👕 ${p.name} has reached ${c.app} appearances.`);
  }
  box.classList.toggle('hidden',!reached.length); if(reached.length)box.innerHTML=`<strong>🏆 Milestones</strong><div>${reached.slice(-4).map(escapeHtml).map(x=>`<div>${x}</div>`).join('')}</div>`;
}
function onboardingSettingsDraft(){const s=loadSettings();return {...s,teamName:$('onboardingTeamName')?.value.trim()||'',teamAbbr:cleanAbbr($('onboardingTeamAbbr')?.value,'YTM'),ageGroup:$('onboardingAgeGroup')?.value||'',season:$('onboardingSeason')?.value.trim()||'2026/27',userRole:$('onboardingRole')?.value||'Parent'}}
function setOnboardingStep(step){['onboardingStep1','onboardingStep2','onboardingStep3','onboardingDone'].forEach(id=>$(id)?.classList.add('hidden'));const target=step===4?'onboardingDone':`onboardingStep${step}`;$(target)?.classList.remove('hidden');if($('onboardingStepLabel'))$('onboardingStepLabel').textContent=step===4?'READY':`${step} of 3`;}
function renderOnboardingSquad(){const ps=loadPlayers(),s=loadSettings(),target=Math.max(1,Number(s.playersOnPitch)||5);if($('onboardingSquadCount'))$('onboardingSquadCount').textContent=`${ps.length} player${ps.length===1?'':'s'}`;if($('onboardingPlayerList'))$('onboardingPlayerList').innerHTML=ps.length?`<div class="gs-onboard-player-grid">${[...ps].sort((a,b)=>(Number(a.number)||999)-(Number(b.number)||999)).map(p=>`<div class="gs-onboard-player">${playerActionTile(p)}<button type="button" class="mini-delete-player" data-id="${p.id}">×</button></div>`).join('')}</div>`:'<p class="muted">Your squad will appear here.</p>';document.querySelectorAll('.mini-delete-player').forEach(btn=>btn.onclick=()=>{savePlayers(loadPlayers().filter(p=>p.id!==btn.dataset.id));renderOnboardingSquad()});const ready=ps.length>=target;if($('finishOnboardingBtn'))$('finishOnboardingBtn').disabled=!ready;if($('onboardingSquadHint'))$('onboardingSquadHint').textContent=ready?`${ps.length} players added. You can add more or finish setup.`:`Add at least ${target} players to field your ${s.matchFormat}v${s.matchFormat} team.`}
function renderOnboarding(){const s=loadSettings();if($('onboardingTeamName'))$('onboardingTeamName').value=s.teamName==='Your Team'?'':s.teamName;if($('onboardingTeamAbbr'))$('onboardingTeamAbbr').value=s.teamAbbr==='YTM'?'':cleanAbbr(s.teamAbbr,'YTM');if($('onboardingAgeGroup'))$('onboardingAgeGroup').value=s.ageGroup||'';if($('onboardingSeason'))$('onboardingSeason').value=s.season||'2026/27';if($('onboardingRole'))$('onboardingRole').value=s.userRole||'Parent';if($('onboardingPrimaryColor'))$('onboardingPrimaryColor').value=s.onboardingPrimaryColor||s.primaryColor||'#25df72';if($('onboardingSecondaryColor'))$('onboardingSecondaryColor').value=s.onboardingSecondaryColor||s.secondaryColor||'#0b2a38';document.querySelectorAll('.format-option').forEach(btn=>btn.classList.toggle('selected',Number(btn.dataset.format)===Number(s.matchFormat)));if($('onboardingTeamCrest'))$('onboardingTeamCrest').textContent=cleanAbbr($('onboardingTeamAbbr')?.value,'YTM');renderOnboardingSquad()}
function openOnboarding(){renderOnboarding();setOnboardingStep(1);showView(views.onboardingView);window.setTimeout(()=>$("onboardingTeamName")?.focus(),80)}
function finishOnboardingV21(){const s=loadSettings();saveSettings({...s,teamName:$('onboardingTeamName').value.trim(),teamAbbr:cleanAbbr($('onboardingTeamAbbr').value,'YTM'),ageGroup:$('onboardingAgeGroup').value,season:$('onboardingSeason').value.trim()||'2026/27',userRole:$('onboardingRole').value,primaryColor:$('onboardingPrimaryColor').value||s.primaryColor||'#25df72',secondaryColor:$('onboardingSecondaryColor').value||s.secondaryColor||'#0b2a38',onboardingPrimaryColor:$('onboardingPrimaryColor').value||'#25df72',onboardingSecondaryColor:$('onboardingSecondaryColor').value||'#0b2a38',onboardingComplete:true});renderOnboarding();$('onboardingCompleteTitle').textContent=`${loadSettings().teamName} is ready.`;$('onboardingCompleteMeta').textContent=`${loadSettings().matchFormat}v${loadSettings().matchFormat} · ${loadPlayers().length} players` ;setOnboardingStep(4)}
function wire(){
  $('newMatchBtn').onclick=()=>{if(!loadSettings().onboardingComplete){openOnboarding();return}openMatchSetup()};
  $('settingsBtn').onclick=()=>showView(views.settingsView);
  $('settingsBackBtn').onclick=()=>showView(views.homeView);
  $('resetAppBtn')?.addEventListener('click',()=>{if(!confirm('Reset GrassSTATory on this device? This deletes the local club, players and matches.'))return;[PLAYER_STORAGE_KEY,SETTINGS_STORAGE_KEY,MATCH_STORAGE_KEY,UPCOMING_STORAGE_KEY].forEach(k=>localStorage.removeItem(k));location.reload();});
  $('matchesNewBtn')?.addEventListener('click',openMatchSetup);
  $('statsUpgradeBtn')?.addEventListener('click',()=>showView(views.platinumView));
  document.querySelectorAll('[name="planPreview"]').forEach(r=>r.addEventListener('change',()=>{const s=loadSettings();saveSettings({...s,planPreview:r.value});updatePlanRadios();refreshIdentity();renderHome();renderStatsView();renderSettings();}));

  $('startPlatinumBtn')?.addEventListener('click',()=>{saveSettings({...loadSettings(),planPreview:'platinum'});renderHome();renderStatsView();alert('Platinum preview enabled for testing.');});
  $('toggleMatchDetailsBtn')?.addEventListener('click',()=>{const p=$('reportDetailsPanel');const hidden=p.classList.toggle('hidden');$('toggleMatchDetailsBtn').textContent=hidden?'Match Details':'Hide Details'});
  $('reportBackBtn')?.addEventListener('click',()=>showView(views.homeView));
  $('reportHomeBtn')?.addEventListener('click',openMatchSetup);
  $('cancelMatchSetupBtn')?.addEventListener('click',()=>showView(views.homeView));
  $('toggleAvailabilityBtn')?.addEventListener('click',()=>{const w=$('availabilityWrap');const hidden=w.classList.toggle('hidden');$('toggleAvailabilityBtn').textContent=hidden?'Change availability':'Done'});
  document.querySelectorAll('[data-match-next]').forEach(btn=>btn.addEventListener('click',()=>setMatchWizardStep(Number(btn.dataset.matchNext))));
  document.querySelectorAll('[data-match-back]').forEach(btn=>btn.addEventListener('click',()=>setMatchWizardStep(Number(btn.dataset.matchBack))));
  setMatchWizardStep(1);
  $('matchSetupForm')?.addEventListener('submit',e=>{e.preventDefault();const ps=loadPlayers(),s=loadSettings(),available=[...(window._available||new Set())],starters=[...(window._starters||new Set())];const opponent=$('opponentName').value.trim();if(!opponent){$('matchSetupError').textContent='Enter the opponent name.';setMatchWizardStep(1);return}if(starters.length!==s.playersOnPitch){$('matchSetupError').textContent=`Select exactly ${s.playersOnPitch} starters.`;return}const team=teamDisplay();const m={id:makeId(),teamName:team.name,teamAbbr:team.abbr,opponent,opponentAbbr:cleanAbbr($('opponentAbbr').value,derivedAbbr(opponent)),date:$('matchDate').value,venue:document.querySelector('input[name="venue"]:checked')?.value||'home',competition:$('matchCompetition').value,availablePlayerIds:available,starterPlayerIds:starters,substitutePlayerIds:available.filter(id=>!starters.includes(id)),currentOnPitch:starters,currentSubs:available.filter(id=>!starters.includes(id)),opponentPlayersOnPitch:s.playersOnPitch,status:'live',period:1,halfTime:false,fullTime:false,periodElapsedSeconds:0,periodStartedAt:null,periodDurations:{},ourScore:0,theirScore:0,events:[],createdAt:new Date().toISOString()};saveMatches([...loadMatches(),m]);startTimerForNewMatch(m.id);});
  $('timerBtn')?.addEventListener('click',()=>{const m=currentMatch();if(m?.periodStartedAt)pauseTimer();else startTimer()});
  $('halfTimeBtn')?.addEventListener('click',halfTime);
  $('startSecondHalfBtn')?.addEventListener('click',startSecond);
  $('fullTimeBtn')?.addEventListener('click',fullTime);
  $('ourGoalBtn')?.addEventListener('click',()=>openGoalDialog('our_goal'));
  $('theirGoalBtn')?.addEventListener('click',()=>openGoalDialog('their_goal'));
  $('subBtn')?.addEventListener('click',openSubDialog);
  $('adjustPlayersBtn')?.addEventListener('click',openAdjust);
  $('undoBtn')?.addEventListener('click',undoLast);
  $('saveGoalBtn')?.addEventListener('click',()=>{const m=currentMatch();if(!m)return;const kind=$('goalDialog').dataset.kind,gt=$('goalType').value,score=kind==='our_goal';const pid=score&&gt!=='own_goal'?$('goalScorer').value:null;const aid=score&&gt!=='own_goal'?($('goalAssist').value||null):null;const og=$('ownGoalPlayer').value||null;recordGoal(kind,gt,pid,aid,og);$('goalDialog').close()});
  $('cancelGoalBtn')?.addEventListener('click',()=>$('goalDialog').close());
  $('goalType')?.addEventListener('change',goalTypeChanged);
  $('subForm')?.addEventListener('submit',e=>{e.preventDefault();saveBatchSubs()});
  $('saveBatchSubsBtn')?.addEventListener('click',e=>{e.preventDefault();saveBatchSubs()});
  $('cancelSubBtn')?.addEventListener('click',()=>$('subDialog').close());
  $('saveAdjustPlayersBtn')?.addEventListener('click',saveAdjust);
  $('cancelAdjustPlayersBtn')?.addEventListener('click',()=>$('adjustPlayersDialog').close());
  $('oppCountMinus')?.addEventListener('click',()=>{adjustOpponentCount=Math.max(0,adjustOpponentCount-1);renderAdjust()});
  $('oppCountPlus')?.addEventListener('click',()=>{adjustOpponentCount=Math.min(20,adjustOpponentCount+1);renderAdjust()});
  $('addPlayerBtn')?.addEventListener('click',()=>openPlayerDialog());
  $('cancelPlayerBtn')?.addEventListener('click',()=>$('playerDialog').close());
  $('playerForm')?.addEventListener('submit',e=>{e.preventDefault();const ps=loadPlayers(),data={name:$('playerName').value.trim(),number:$('playerNumber').value.trim(),position:$('playerPosition').value};if(!data.name)return;if(editingPlayerId){const p=ps.find(x=>x.id===editingPlayerId);if(p)Object.assign(p,data)}else ps.push({id:makeId(),...data});savePlayers(ps);$('playerDialog').close();renderPlayers();});
  $('deletePlayerBtn')?.addEventListener('click',()=>{if(!editingPlayerId)return;savePlayers(loadPlayers().filter(p=>p.id!==editingPlayerId));$('playerDialog').close();renderPlayers()});
  $('fillTestPlayersBtn')?.addEventListener('click',()=>{const s=loadSettings(),ps=loadPlayers();for(let i=ps.length+1;i<=Math.max(s.playersOnPitch+3,10);i++)ps.push({id:makeId(),name:`Player ${i}`,number:String(i),position:''});savePlayers(ps);renderPlayers();});
  $('settingsForm')?.addEventListener('submit',e=>{e.preventDefault();const s=loadSettings();saveSettings({...s,teamName:$('teamName').value.trim()||'Your Team',teamAbbr:cleanAbbr($('teamAbbr').value,'YTM'),matchFormat:Number($('matchFormat').value)||5,playersOnPitch:Number($('playersOnPitch').value)||Number($('matchFormat').value)||5,ageGroup:$('ageGroup').value,season:$('season').value.trim()||'2026/27',primaryColor:$('primaryColor').value,secondaryColor:$('secondaryColor').value});$('settingsSaved').textContent='Saved';refreshIdentity();renderSettings();setTimeout(()=>$('settingsSaved').textContent='',1200)});
  $('matchFormat')?.addEventListener('change',()=>{$('playersOnPitch').value=$('matchFormat').value});
  $('onboardingNext1')?.addEventListener('click',()=>{if(!$('onboardingTeamName').value.trim()){alert('Enter your team name.');return}const s=loadSettings();saveSettings({...s,teamName:$('onboardingTeamName').value.trim(),teamAbbr:cleanAbbr($('onboardingTeamAbbr').value,'YTM'),ageGroup:$('onboardingAgeGroup').value,season:$('onboardingSeason').value.trim()||'2026/27',userRole:$('onboardingRole').value,primaryColor:$('onboardingPrimaryColor').value||'#25df72',secondaryColor:$('onboardingSecondaryColor').value||'#0b2a38',onboardingPrimaryColor:$('onboardingPrimaryColor').value||'#25df72',onboardingSecondaryColor:$('onboardingSecondaryColor').value||'#0b2a38'});renderOnboarding();setOnboardingStep(2)});
  $('onboardingBack2')?.addEventListener('click',()=>setOnboardingStep(1));
  document.querySelectorAll('.format-option').forEach(btn=>btn.addEventListener('click',()=>{const f=Number(btn.dataset.format);saveSettings({...loadSettings(),matchFormat:f,playersOnPitch:f});document.querySelectorAll('.format-option').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');renderOnboarding()}));
  $('onboardingNext2')?.addEventListener('click',()=>{renderOnboardingSquad();setOnboardingStep(3)});
  $('onboardingBack3')?.addEventListener('click',()=>setOnboardingStep(2));
  $('quickAddPlayerBtn')?.addEventListener('click',()=>{const name=$('quickPlayerName').value.trim();if(!name)return;const ps=loadPlayers();ps.push({id:makeId(),name,number:$('quickPlayerNumber').value.trim(),position:$('quickPlayerPosition').value});savePlayers(ps);$('quickPlayerName').value='';$('quickPlayerNumber').value='';$('quickPlayerPosition').value='';renderOnboardingSquad()});
  $('onboardingTestSquadBtn')?.addEventListener('click',()=>{$('fillTestPlayersBtn')?.click();renderOnboardingSquad()});
  $('finishOnboardingBtn')?.addEventListener('click',finishOnboardingV21);
  $('onboardingGoHomeBtn')?.addEventListener('click',()=>{closeOnboarding();showView(views.homeView)});
  document.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>{const n=btn.dataset.nav;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('is-active',b===btn));const target={home:views.homeView,matches:views.matchesView,stats:views.statsView,team:views.settingsView,settings:views.settingsView}[n]||views.homeView;showView(target);if(n==='stats')requestAnimationFrame(renderStatsView)}));
  $('statsFilterRow')?.querySelectorAll('[data-stats-filter]').forEach(btn=>btn.addEventListener('click',()=>{statsFilter=btn.dataset.statsFilter;document.querySelectorAll('[data-stats-filter]').forEach(b=>b.classList.toggle('active-filter',b===btn));renderStatsView()}));
  $('shareResultBtn')?.addEventListener('click',()=>{const m=currentMatchReport;if(!m)return;const text=`${m.teamName} ${m.ourScore}-${m.theirScore} ${m.opponent} · ${m.competition}`;if(navigator.share)navigator.share({title:'GrassStatory match result',text});else navigator.clipboard?.writeText(text).then(()=>alert('Result copied to clipboard.'))});
  $('shareMilestoneWatchBtn')?.addEventListener('click',()=>{const txt=[...document.querySelectorAll('#milestoneWatchList .milestone-row')].map(x=>x.textContent).join('\n');if(navigator.share)navigator.share({title:'GrassStatory milestone watch',text:txt});else navigator.clipboard?.writeText(txt).then(()=>alert('Milestones copied to clipboard.'))});
  $('shareLiveBtn')?.addEventListener('click',()=>{const m=currentMatch();if(!m)return;const text=`Live on GrassStatory: ${m.teamName} ${m.ourScore}-${m.theirScore} ${m.opponent}`;if(navigator.share)navigator.share({title:'GrassStatory Live Match',text});else navigator.clipboard?.writeText(text).then(()=>alert('Live match text copied to clipboard.'))});
  $('opponentName')?.addEventListener('input',()=>{$('setupOpponentPreviewName').textContent=$('opponentName').value.trim()||'Add opponent details';$('setupOpponentCrest').textContent=cleanAbbr($('opponentAbbr').value,derivedAbbr($('opponentName').value,'OPP'))});
  $('opponentAbbr')?.addEventListener('input',()=>{$('setupOpponentCrest').textContent=cleanAbbr($('opponentAbbr').value,derivedAbbr($('opponentName').value,'OPP'))});
  $('onboardingTeamName')?.addEventListener('input',()=>{$('onboardingTeamCrest').textContent=cleanAbbr($('onboardingTeamAbbr').value,derivedAbbr($('onboardingTeamName').value,'YTM'))});
  $('onboardingTeamAbbr')?.addEventListener('input',()=>{$('onboardingTeamCrest').textContent=cleanAbbr($('onboardingTeamAbbr').value,'YTM')});$('onboardingPrimaryColor')?.addEventListener('input',()=>applyCrestStyle($('onboardingTeamCrest'),$('onboardingPrimaryColor').value,$('onboardingSecondaryColor').value));$('onboardingSecondaryColor')?.addEventListener('input',()=>applyCrestStyle($('onboardingTeamCrest'),$('onboardingPrimaryColor').value,$('onboardingSecondaryColor').value));
}
function closeOnboarding(){$('onboardingView')?.classList.add('hidden')}
function startTimerForNewMatch(id){activeMatchId=id;const m=currentMatch();if(!m)return;showView(views.liveMatchView);startTimer()}

refreshIdentity();wire();renderHome();renderSettings();if(!loadSettings().onboardingComplete)openOnboarding();

function renderTeamPreview(){
 const box=$('teamPreviewList'),btn=$('addTeamPreviewBtn'); if(!box||!btn)return;
 const s=loadSettings(),teams=loadJson('grassstatory.teamsPreview',[]);
 box.innerHTML=`<div class="summary-row"><strong>${escapeHtml(s.teamName||'Current team')}</strong><span>Current</span></div>`+teams.map(t=>`<div class="summary-row"><strong>${escapeHtml(t.name)}</strong><span>Preview team</span></div>`).join('');
 btn.disabled=s.planPreview!=='platinum'; btn.textContent=s.planPreview==='platinum'?'＋ Add Team':'＋ Add Team 🔒 Platinum';
 btn.onclick=()=>{if(s.planPreview!=='platinum'){showView(views.platinumView);return}const name=prompt('Team name');if(!name)return;teams.push({id:makeId(),name:name.trim()});saveJson('grassstatory.teamsPreview',teams);renderTeamPreview()};
}
