(()=>{
'use strict';
const VERSION='2.0.0';
const NS='grassstatory.fresh.v2';
const app=document.getElementById('app');
const overlay=document.getElementById('overlay');
const toastEl=document.getElementById('toast');
const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const id=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const today=()=>new Date().toISOString().slice(0,10);
const defaultState=()=>({
  settings:{onboardingComplete:false,clubName:'',shortName:'',ageGroup:'U12',season:'2026/27',matchFormat:5,homePrimary:'#0c7a44',homeSecondary:'#f4f3ec',awayPrimary:'#d5b153',awaySecondary:'#10293b'},
  players:[],matches:[],moments:[],activeMatchId:null
});
let data=load();
let route=data.settings.onboardingComplete?'home':'splash';
let onboardStep=1,matchStep=1,statsTab='players',cardMode='home';
let draftPlayer={name:'',number:'',position:'Forward'};
let draftMatch=null;
let goalFlow=null,subFlow=null;
let timerHandle=null;

function load(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(NS)||'{}'))}catch{return defaultState()}}
function save(){localStorage.setItem(NS,JSON.stringify(data))}
function reset(){localStorage.removeItem(NS);data=defaultState();route='splash';onboardStep=1;draftMatch=null;goalFlow=null;subFlow=null;stopTick();render()}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1200)}
function setRoute(r){route=r;closeOverlay();window.scrollTo(0,0);render()}
function formatDate(s){if(!s)return'';try{return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00'))}catch{return s}}
function initials(name,fallback='GST'){const words=String(name||'').trim().split(/\s+/).filter(Boolean);return (words.length>1?(words[0][0]+words[1][0]):words[0]?.slice(0,3)||fallback).toUpperCase()}
function crestHtml(abbr,p,s,size=''){return `<div class="crest ${size}" style="--c1:${esc(p)};--c2:${esc(s)}"><b>${esc(abbr||'GST')}</b></div>`}
function settings(){return data.settings}
function playerBy(id){return data.players.find(p=>p.id===id)}
function activeMatch(){return data.matches.find(m=>m.id===data.activeMatchId)||null}
function completedMatches(){return data.matches.filter(m=>m.status==='completed').sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||''))}
function currentMinute(m){return Math.floor(currentSeconds(m)/60)+1}
function currentSeconds(m){if(!m)return 0;return (m.clockSeconds||0)+(m.runningSince?Math.max(0,Math.floor((Date.now()-m.runningSince)/1000)):0)}
function pauseClock(m){if(!m||!m.runningSince)return;m.clockSeconds=currentSeconds(m);m.runningSince=null;save()}
function startClock(m){if(!m||m.runningSince||m.status!=='live')return;m.runningSince=Date.now();save();startTick()}
function stopTick(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function startTick(){stopTick();timerHandle=setInterval(()=>{if(route==='live')updateClockDom();else stopTick()},1000)}
function updateClockDom(){const m=activeMatch(),el=qs('#liveClock');if(!m||!el)return;const s=currentSeconds(m);el.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function goalCount(playerId,excludeCurrentEventId=null){let n=0;for(const m of data.matches){for(const e of m.events||[]){if(e.id===excludeCurrentEventId)continue;if(e.type==='our_goal'&&e.scorerId===playerId&&e.goalType!=='Own Goal')n++}}return n}
function assistCount(playerId){let n=0;for(const m of data.matches)for(const e of m.events||[])if(e.type==='our_goal'&&e.assistId===playerId&&e.goalType!=='Own Goal')n++;return n}
function appCount(playerId){let n=0;for(const m of completedMatches()){const participants=new Set(m.starterIds||[]);for(const e of m.events||[])if(e.type==='sub'&&e.onId)participants.add(e.onId);if(participants.has(playerId))n++}return n}
function playerStats(){return data.players.map(p=>({p,apps:appCount(p.id),goals:goalCount(p.id),assists:assistCount(p.id),starts:completedMatches().filter(m=>(m.starterIds||[]).includes(p.id)).length})).sort((a,b)=>b.goals-a.goals||b.apps-a.apps||(Number(a.p.number)||999)-(Number(b.p.number)||999))}
function teamStats(){const ms=completedMatches();let w=0,d=0,l=0,gf=0,ga=0;ms.forEach(m=>{gf+=m.ourScore;ga+=m.theirScore;if(m.ourScore>m.theirScore)w++;else if(m.ourScore<m.theirScore)l++;else d++});return{played:ms.length,w,d,l,gf,ga}}
function resultLetter(m){return m.ourScore>m.theirScore?'W':m.ourScore<m.theirScore?'L':'D'}
function upcomingMoments(){const items=[];const stats=playerStats();for(const x of stats){for(const t of [5,10,25,50])if(x.goals<t&&t-x.goals<=2){items.push({key:'g'+x.p.id+t,label:x.p.name,detail:`${t-x.goals} goal${t-x.goals===1?'':'s'} from ${t}`,progress:`${x.goals}/${t}`,number:x.p.number});break}for(const t of [10,25,50,100])if(x.apps<t&&t-x.apps<=2){items.push({key:'a'+x.p.id+t,label:x.p.name,detail:`${t-x.apps} appearance${t-x.apps===1?'':'s'} from ${t}`,progress:`${x.apps}/${t}`,number:x.p.number});break}}
 const ts=teamStats();for(const t of [10,25,50])if(ts.gf<t&&t-ts.gf<=3){items.unshift({key:'team'+t,label:'Team',detail:`${t-ts.gf} goal${t-ts.gf===1?'':'s'} from ${t} this season`,progress:`${ts.gf}/${t}`,number:'★'});break}
 return items.slice(0,3)
}
function cardVars(mode='home'){const s=settings();return mode==='away'?{p:s.awayPrimary,s:s.awaySecondary}:{p:s.homePrimary,s:s.homeSecondary}}
function playerCard(p,mode='home',klass='player-preview'){const c=cardVars(mode);return `<article class="${klass}" style="--p:${c.p};--s:${c.s}"><div class="pc-club">${esc(settings().clubName||'Your Club')}</div><div class="pc-badge">${crestHtml(settings().shortName||initials(settings().clubName),c.p,c.s,'tiny')}</div><div class="pc-name">${esc((p.name||'Player').toUpperCase())}</div><div class="pc-number">${esc(p.number||'0')}</div><div class="pc-pos">${esc((p.position||'Player').toUpperCase())}</div><div class="pc-sign">${esc(p.name||'Player')}</div></article>`}
function tileHtml(p,selected=false,mode='home'){const c=cardVars(mode);return `<article class="id-tile ${selected?'selected':''}" style="--p:${c.p};--s:${c.s}" data-player-id="${esc(p.id)}"><div class="tile-check">${selected?'✓':''}</div><div class="tile-club">${esc(settings().shortName||initials(settings().clubName))}</div><div class="tile-number">${esc(p.number||'–')}</div><div class="tile-name">${esc(p.name)}</div><div class="tile-pos">${esc(p.position||'Player')}</div><div class="tile-sign">${esc(p.name)}</div></article>`}
function nav(active='home'){return `<nav class="bottom-nav"><button data-route="home" class="${active==='home'?'active':''}">⌂<span>Home</span></button><button data-route="matches" class="${active==='matches'?'active':''}">▣<span>Matches</span></button><button data-route="squad" class="${active==='squad'?'active':''}">♟<span>Squad</span></button><button data-route="stats" class="${active==='stats'?'active':''}">▥<span>Stats</span></button><button data-route="settings" class="${active==='settings'?'active':''}">⋯<span>More</span></button></nav>`}
function pagebar(title,back=null,right=''){return `<header class="pagebar"><button class="icon-btn" ${back?`data-route="${back}"`:''}>${back?'‹':'☰'}</button><h1>${esc(title)}</h1>${right||'<span></span>'}</header>`}

function render(){stopTick();if(route==='splash')renderSplash();else if(route==='onboarding')renderOnboarding();else if(route==='home')renderHome();else if(route==='squad')renderSquad();else if(route==='matches')renderMatches();else if(route==='matchSetup')renderMatchSetup();else if(route==='live')renderLive();else if(route==='result')renderResult();else if(route==='stats')renderStats();else if(route==='settings')renderSettings();else renderHome();wireCommon();if(route==='live')startTick()}
function renderSplash(){app.innerHTML=`<main class="screen no-nav splash"><div class="splash-inner"><div class="splash-ball">⚽</div><h1>Grass<span>STAT</span>ory</h1><p>Your football.<br>Your stats.<br>Your story.</p><div class="premium-label">PREMIUM · v${VERSION}</div><button class="primary-btn" id="enterApp">Get Started ›</button></div></main>`;qs('#enterApp').onclick=()=>{route=settings().onboardingComplete?'home':'onboarding';render()}}
function renderOnboarding(){if(onboardStep===1)renderClubSetup();else renderPlayerSetup()}
function renderClubSetup(){const s=settings();app.innerHTML=`<main class="screen no-nav onboard"><section class="onboard-head"><div class="step-line"><span>FIRST TIME SETUP</span><span>1 OF 2</span></div><h1>Create your club</h1><p>Set the club identity once. Home and away colours will drive player cards, match graphics and Moments.</p></section><section class="panel"><label class="field"><span>Club name</span><input id="clubName" value="${esc(s.clubName)}" placeholder="Riverside Athletic"></label><div class="grid2"><label class="field"><span>Short name</span><input id="shortName" value="${esc(s.shortName)}" maxlength="4" placeholder="RIV"></label><label class="field"><span>Age group</span><input id="ageGroup" value="${esc(s.ageGroup)}" placeholder="U12"></label></div><label class="field"><span>Season</span><input id="season" value="${esc(s.season)}" placeholder="2026/27"></label><div class="field"><span>Match format</span><div class="format-row">${[5,7,9,11].map(n=>`<button type="button" data-format="${n}" class="${s.matchFormat===n?'selected':''}">${n}v${n}</button>`).join('')}</div></div><div class="separator"></div><h3 class="compact-title">Home colours</h3><div class="palette-preview" id="homePalette" style="--p:${s.homePrimary};--s:${s.homeSecondary}"><strong>HOME</strong></div><div class="colour-grid"><label class="colour-field"><span>Primary</span><input id="homePrimary" type="color" value="${s.homePrimary}"></label><label class="colour-field"><span>Secondary</span><input id="homeSecondary" type="color" value="${s.homeSecondary}"></label></div><div class="separator"></div><h3 class="compact-title">Away colours</h3><div class="palette-preview" id="awayPalette" style="--p:${s.awayPrimary};--s:${s.awaySecondary}"><strong>AWAY</strong></div><div class="colour-grid"><label class="colour-field"><span>Primary</span><input id="awayPrimary" type="color" value="${s.awayPrimary}"></label><label class="colour-field"><span>Secondary</span><input id="awaySecondary" type="color" value="${s.awaySecondary}"></label></div><button class="primary-btn" id="clubNext" style="margin-top:16px">Build your squad ›</button></section></main>`;
 const syncClubFields=()=>{s.clubName=qs('#clubName').value;s.shortName=qs('#shortName').value.toUpperCase().slice(0,4);s.ageGroup=qs('#ageGroup').value;s.season=qs('#season').value;save()};['clubName','shortName','ageGroup','season'].forEach(k=>qs('#'+k).oninput=syncClubFields);qsa('[data-format]').forEach(b=>b.onclick=()=>{syncClubFields();s.matchFormat=Number(b.dataset.format);save();qsa('[data-format]').forEach(x=>x.classList.toggle('selected',x===b))});['homePrimary','homeSecondary','awayPrimary','awaySecondary'].forEach(k=>qs('#'+k).oninput=e=>{syncClubFields();s[k]=e.target.value;save();const el=k.startsWith('home')?qs('#homePalette'):qs('#awayPalette');el.style.setProperty('--p',s[k.startsWith('home')?'homePrimary':'awayPrimary']);el.style.setProperty('--s',s[k.startsWith('home')?'homeSecondary':'awaySecondary'])});qs('#clubNext').onclick=()=>{syncClubFields();s.clubName=s.clubName.trim();s.shortName=(s.shortName.trim()||initials(s.clubName)).toUpperCase().slice(0,4);s.ageGroup=s.ageGroup.trim();s.season=s.season.trim()||'2026/27';if(!s.clubName){toast('Enter your club name');return}save();onboardStep=2;render()}}
function renderPlayerSetup(){const s=settings();const p={id:'preview',name:draftPlayer.name||'Player',number:draftPlayer.number||'9',position:draftPlayer.position};app.innerHTML=`<main class="screen no-nav onboard"><section class="onboard-head"><div class="step-line"><span>FIRST TIME SETUP</span><span>2 OF 2</span></div><h1>Build your squad</h1><p>Create each player's identity card from their details. Add at least ${s.matchFormat} players to finish setup.</p></section><section class="panel">${playerCard(p,'home')}<div class="player-form"><label class="field"><span>Player name</span><input id="newPlayerName" value="${esc(draftPlayer.name)}" placeholder="Player name"></label><label class="field"><span>Number</span><input id="newPlayerNumber" value="${esc(draftPlayer.number)}" inputmode="numeric" maxlength="3" placeholder="#"></label><label class="field position"><span>Position</span><select id="newPlayerPosition">${['Goalkeeper','Defender','Midfielder','Forward','Player'].map(x=>`<option ${draftPlayer.position===x?'selected':''}>${x}</option>`).join('')}</select></label></div><button class="primary-btn" id="addPlayer" style="margin-top:10px">Add player to squad ›</button></section><section class="panel"><div class="section-head"><h2>${data.players.length} players</h2><span>${data.players.length>=s.matchFormat?'Ready':'Need '+Math.max(0,s.matchFormat-data.players.length)}</span></div><div class="squad-list">${data.players.length?data.players.map(p=>`<div class="squad-row">${tileHtml(p)}<div><strong>${esc(p.name)}</strong><small>#${esc(p.number)} · ${esc(p.position)}</small></div><button class="delete" data-delete-player="${p.id}">×</button></div>`).join(''):'<div class="empty">Your squad will appear here.</div>'}</div><div class="button-row" style="margin-top:14px"><button class="secondary-btn" id="backClub">Back</button><button class="primary-btn" id="finishSetup" ${data.players.length<s.matchFormat?'disabled':''}>Finish setup</button></div></section></main>`;
 const syncPlayerPreview=()=>{draftPlayer={name:qs('#newPlayerName').value,number:qs('#newPlayerNumber').value.replace(/\D/g,'').slice(0,3),position:qs('#newPlayerPosition').value};qs('.pc-name').textContent=(draftPlayer.name||'Player').toUpperCase();qs('.pc-number').textContent=draftPlayer.number||'9';qs('.pc-pos').textContent=(draftPlayer.position||'Player').toUpperCase();qs('.pc-sign').textContent=draftPlayer.name||'Player'};['newPlayerName','newPlayerNumber','newPlayerPosition'].forEach(k=>qs('#'+k).oninput=syncPlayerPreview);qs('#addPlayer').onclick=()=>{syncPlayerPreview();const name=draftPlayer.name.trim(),number=draftPlayer.number,position=draftPlayer.position;if(!name){toast('Enter a player name');return}data.players.push({id:id(),name,number,position});draftPlayer={name:'',number:'',position:'Forward'};save();renderPlayerSetup()};qsa('[data-delete-player]').forEach(b=>b.onclick=()=>{data.players=data.players.filter(p=>p.id!==b.dataset.deletePlayer);save();renderPlayerSetup()});qs('#backClub').onclick=()=>{onboardStep=1;render()};qs('#finishSetup').onclick=()=>{if(data.players.length<s.matchFormat){toast(`Add at least ${s.matchFormat} players`);return}s.onboardingComplete=true;save();setRoute('home')}}

function renderHome(){const s=settings(),mom=upcomingMoments(),recent=completedMatches().slice(0,5);app.innerHTML=`<main class="screen"><section class="hero"><header class="topbar"><button class="icon-btn" data-route="settings">☰</button><div class="wordmark">Grass<span>STAT</span>ory</div><button class="icon-btn" data-route="settings">⚙</button></header><div class="club-lockup">${crestHtml(s.shortName||initials(s.clubName),s.homePrimary,s.homeSecondary)}<h1>${esc(s.clubName)}</h1><p>${esc(s.ageGroup)} · ${esc(s.season)}</p></div><button class="primary-btn" id="createMatch">Create Match ›</button></section><section class="stack"><div class="section-head"><h2>Upcoming Moments</h2><button data-route="stats" data-tab="moments">View all ›</button></div><div class="surface moment-list">${mom.length?mom.map(x=>`<article class="moment"><div class="mini-id" style="--p:${s.homePrimary};--s:${s.homeSecondary}">${esc(x.number||'★')}</div><div><strong>${esc(x.label)}</strong><small>${esc(x.detail)}</small></div><b>${esc(x.progress)}</b></article>`).join(''):'<div class="empty">Play matches and upcoming milestones will appear here.</div>'}</div><div class="section-head results-head"><h2>Recent Results</h2><button data-route="matches">View all ›</button></div><div class="surface results">${recent.length?recent.map(m=>`<button class="results-row" data-report="${m.id}" style="width:100%;border-left:0;border-right:0;background:transparent;color:#fff;text-align:left"><i class="result-pill ${resultLetter(m).toLowerCase()}">${resultLetter(m)}</i><span>${esc(m.venue==='away'?m.opponent:s.clubName)}</span><strong>${m.venue==='away'?`${m.theirScore}–${m.ourScore}`:`${m.ourScore}–${m.theirScore}`}</strong><span>${esc(m.venue==='away'?s.clubName:m.opponent)}</span><time>${formatDate(m.date)}</time></button>`).join(''):'<div class="empty">No results yet. Create your first match.</div>'}</div><div class="home-actions"><button data-route="stats" data-tab="players">Player Stats<span>Players & performance</span></button><button data-route="stats" data-tab="season">Season Stats<span>Results & trends</span></button><button data-route="stats" data-tab="moments">Moments<span>Milestones & memories</span></button></div></section>${nav('home')}</main>`;qs('#createMatch').onclick=()=>openMatchSetup();wireReports()}
function renderSquad(){app.innerHTML=`<main class="screen">${pagebar('Squad','home','<button class="text-btn" id="addSquadPlayer">＋ Add</button>')}<section class="stack"><h2 class="screen-title">${data.players.length} players</h2><p class="hint">Tap a player tile to edit their name, number or position.</p><div class="squad-compact">${data.players.map(p=>tileHtml(p)).join('')}</div></section>${nav('squad')}</main>`;qs('#addSquadPlayer').onclick=()=>openPlayerEditor();qsa('.id-tile').forEach(t=>t.onclick=()=>openPlayerEditor(playerBy(t.dataset.playerId)))}
function openPlayerEditor(existing=null){const p=existing?{...existing}:{id:null,name:'',number:'',position:'Forward'};const preview={id:'preview',name:p.name||'Player',number:p.number||'9',position:p.position||'Forward'};openOverlay(`<div class="modal"><div class="modal-head"><h2>${existing?'Edit Player':'Add Player'}</h2><button class="icon-btn" data-close-overlay>×</button></div><div class="modal-body">${playerCard(preview,'home')}<div class="player-form" style="margin-top:14px"><label class="field"><span>Player name</span><input id="editPlayerName" value="${esc(p.name)}" placeholder="Player name"></label><label class="field"><span>Number</span><input id="editPlayerNumber" value="${esc(p.number)}" inputmode="numeric" maxlength="3" placeholder="#"></label><label class="field position"><span>Position</span><select id="editPlayerPosition">${['Goalkeeper','Defender','Midfielder','Forward','Player'].map(x=>`<option ${p.position===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="flow-actions">${existing?'<button class="secondary-btn danger-btn" id="deleteEditedPlayer">Delete</button>':'<button class="secondary-btn" data-close-overlay>Cancel</button>'}<button class="primary-btn" id="saveEditedPlayer">${existing?'Save Changes':'Add Player'}</button></div></div></div>`);const sync=()=>{const name=qs('#editPlayerName',overlay).value||'Player',num=qs('#editPlayerNumber',overlay).value.replace(/\D/g,'').slice(0,3)||'9',pos=qs('#editPlayerPosition',overlay).value;qs('.pc-name',overlay).textContent=name.toUpperCase();qs('.pc-number',overlay).textContent=num;qs('.pc-pos',overlay).textContent=pos.toUpperCase();qs('.pc-sign',overlay).textContent=name};['editPlayerName','editPlayerNumber','editPlayerPosition'].forEach(k=>qs('#'+k,overlay).oninput=sync);qs('#saveEditedPlayer',overlay).onclick=()=>{const name=qs('#editPlayerName',overlay).value.trim(),number=qs('#editPlayerNumber',overlay).value.replace(/\D/g,'').slice(0,3),position=qs('#editPlayerPosition',overlay).value;if(!name){toast('Enter a player name');return}if(existing){Object.assign(existing,{name,number,position})}else data.players.push({id:id(),name,number,position});save();closeOverlay();renderSquad()};if(existing)qs('#deleteEditedPlayer',overlay).onclick=()=>{if(data.matches.some(m=>m.status==='live'&&(m.availableIds||[]).includes(existing.id))){toast('Cannot delete a player in the live match');return}data.players=data.players.filter(x=>x.id!==existing.id);save();closeOverlay();renderSquad()}}

function renderMatches(){const ms=completedMatches();app.innerHTML=`<main class="screen">${pagebar('Matches','home')}<section class="stack"><h2 class="screen-title">Match history</h2><div style="display:grid;gap:10px">${ms.length?ms.map(m=>`<button class="history-card" data-report="${m.id}"><span><strong>${formatDate(m.date)}</strong><br><small>${esc(m.competition)}</small></span><span><strong>${esc(settings().clubName)} ${m.ourScore}–${m.theirScore} ${esc(m.opponent)}</strong><br><small>${esc(m.venue==='away'?'Away':'Home')} · ${resultLetter(m)}</small></span><b>›</b></button>`).join(''):'<div class="empty surface">No completed matches yet.</div>'}</div></section>${nav('matches')}</main>`;wireReports()}

function openMatchSetup(){if(data.players.length<settings().matchFormat){toast(`Add at least ${settings().matchFormat} players first`);return}draftMatch={opponent:'',oppAbbr:'',oppPrimary:'#315f9d',oppSecondary:'#f4f3ec',date:today(),time:'10:00',competition:'League',venue:'home',available:new Set(data.players.map(p=>p.id)),starters:new Set(data.players.slice(0,settings().matchFormat).map(p=>p.id))};matchStep=1;setRoute('matchSetup')}
function renderMatchSetup(){if(!draftMatch){openMatchSetup();return}const d=draftMatch,s=settings();let body='';if(matchStep===1){body=`<div class="step-title"><span class="step-badge">1</span><div><span class="eyebrow">OPPONENT</span><h2>Who are you playing?</h2></div></div><label class="field"><span>Opponent</span><input id="oppName" value="${esc(d.opponent)}" placeholder="Oakwood FC"></label><label class="field"><span>Abbreviation</span><input id="oppAbbr" value="${esc(d.oppAbbr)}" maxlength="4" placeholder="OAK"></label><div class="opp-preview"><div class="opp-card" id="oppCard" style="--p:${d.oppPrimary};--s:${d.oppSecondary}">${esc(d.oppAbbr||'OPP')}</div><div><span class="eyebrow">OPPONENT IDENTITY</span><h3 id="oppPreviewName">${esc(d.opponent||'Opponent')}</h3><p class="muted">Colours are saved with this match.</p></div></div><div class="colour-grid"><label class="colour-field"><span>Primary</span><input id="oppPrimary" type="color" value="${d.oppPrimary}"></label><label class="colour-field"><span>Secondary</span><input id="oppSecondary" type="color" value="${d.oppSecondary}"></label></div>`}
 else if(matchStep===2){body=`<div class="step-title"><span class="step-badge">2</span><div><span class="eyebrow">MATCH DETAILS</span><h2>When and where?</h2></div></div><div class="grid2"><label class="field"><span>Date</span><input id="matchDate" type="date" value="${d.date}"></label><label class="field"><span>Kick off</span><input id="matchTime" type="time" value="${d.time}"></label></div><label class="field"><span>Competition</span><select id="competition"><option ${d.competition==='League'?'selected':''}>League</option><option ${d.competition==='Cup'?'selected':''}>Cup</option><option ${d.competition==='Friendly'?'selected':''}>Friendly</option><option ${d.competition==='Tournament'?'selected':''}>Tournament</option></select></label><label class="field"><span>Venue</span><select id="venue"><option value="home" ${d.venue==='home'?'selected':''}>Home</option><option value="away" ${d.venue==='away'?'selected':''}>Away</option></select></label><div class="surface" style="padding:14px"><strong>${s.matchFormat}v${s.matchFormat}</strong><p class="hint">Your club format is used for the starting lineup. Everyone else selected is automatically on the bench.</p></div>`}
 else if(matchStep===3){body=`<div class="step-title"><span class="step-badge">3</span><div><span class="eyebrow">MATCH SQUAD</span><h2>Who's available?</h2></div></div><div class="select-panel"><div class="select-meta"><strong>${d.available.size} selected</strong><span class="pill">Need ${s.matchFormat}+</span></div><div class="squad-compact">${data.players.map(p=>tileHtml(p,d.available.has(p.id))).join('')}</div></div>`}
 else{const available=data.players.filter(p=>d.available.has(p.id));const bench=available.filter(p=>!d.starters.has(p.id));body=`<div class="step-title"><span class="step-badge">4</span><div><span class="eyebrow">STARTING TEAM</span><h2>Select your starting ${s.matchFormat}</h2></div></div><div class="select-panel"><div class="select-meta"><strong>${d.starters.size} / ${s.matchFormat}</strong><span class="pill">Tap to select</span></div><div class="squad-compact">${available.map(p=>tileHtml(p,d.starters.has(p.id))).join('')}</div></div><h3>Bench <span class="muted">(${bench.length})</span></h3><div class="bench-strip">${bench.length?bench.map(p=>`<div class="bench-item"><strong>${esc(p.number)} · ${esc(p.name)}</strong><small>${esc(p.position)}</small></div>`).join(''):'<span class="muted">No substitutes.</span>'}</div>`}
 app.innerHTML=`<main class="screen no-nav"><section class="wizard"><div class="wizard-head"><div><span class="eyebrow">MATCH LOBBY · ${matchStep} OF 4</span><h1>${matchStep===1?'New Match':matchStep===2?'Match Details':matchStep===3?'Match Squad':'Starting Lineup'}</h1><p>Set up the match in four quick steps.</p></div><button class="text-btn" data-route="home">Cancel</button></div><section class="panel" style="margin:16px 0">${body}<div class="button-row" style="margin-top:18px"><button class="secondary-btn" id="wizardBack">${matchStep===1?'Cancel':'Back'}</button><button class="primary-btn" id="wizardNext">${matchStep===4?'Start Match':'Next'}</button></div></section></section></main>`;wireMatchSetup()}
function wireMatchSetup(){const d=draftMatch;if(matchStep===1){const sync=()=>{d.opponent=qs('#oppName').value;d.oppAbbr=qs('#oppAbbr').value.toUpperCase().slice(0,4);d.oppPrimary=qs('#oppPrimary').value;d.oppSecondary=qs('#oppSecondary').value;qs('#oppPreviewName').textContent=d.opponent||'Opponent';const c=qs('#oppCard');c.textContent=d.oppAbbr||initials(d.opponent,'OPP');c.style.background=`linear-gradient(145deg,${d.oppPrimary} 0 55%,${d.oppSecondary} 55%)`};qsa('#oppName,#oppAbbr,#oppPrimary,#oppSecondary').forEach(x=>x.oninput=sync)}else if(matchStep===2){qs('#matchDate').onchange=e=>d.date=e.target.value;qs('#matchTime').onchange=e=>d.time=e.target.value;qs('#competition').onchange=e=>d.competition=e.target.value;qs('#venue').onchange=e=>d.venue=e.target.value}else if(matchStep===3){qsa('.id-tile').forEach(t=>t.onclick=()=>{const pid=t.dataset.playerId;if(d.available.has(pid)){d.available.delete(pid);d.starters.delete(pid)}else d.available.add(pid);renderMatchSetup()})}else{qsa('.id-tile').forEach(t=>t.onclick=()=>{const pid=t.dataset.playerId;if(d.starters.has(pid))d.starters.delete(pid);else if(d.starters.size<settings().matchFormat)d.starters.add(pid);else toast(`Select ${settings().matchFormat} starters`);renderMatchSetup()})}
 qs('#wizardBack').onclick=()=>{if(matchStep===1){setRoute('home')}else{matchStep--;renderMatchSetup()}};qs('#wizardNext').onclick=()=>{if(matchStep===1){if(!d.opponent.trim()){toast('Enter the opponent');return}d.oppAbbr=d.oppAbbr||initials(d.opponent,'OPP');matchStep++}else if(matchStep===2)matchStep++;else if(matchStep===3){if(d.available.size<settings().matchFormat){toast(`Select at least ${settings().matchFormat} players`);return}d.starters=new Set([...d.starters].filter(x=>d.available.has(x)));if(d.starters.size!==settings().matchFormat)d.starters=new Set([...d.available].slice(0,settings().matchFormat));matchStep++}else{if(d.starters.size!==settings().matchFormat){toast(`Select exactly ${settings().matchFormat} starters`);return}startMatch();return}renderMatchSetup()}}
function startMatch(){const d=draftMatch,available=[...d.available],starters=[...d.starters],subs=available.filter(x=>!d.starters.has(x));const m={id:id(),opponent:d.opponent,oppAbbr:d.oppAbbr||initials(d.opponent,'OPP'),oppPrimary:d.oppPrimary,oppSecondary:d.oppSecondary,date:d.date,time:d.time,competition:d.competition,venue:d.venue,availableIds:available,starterIds:starters,subIds:subs,onPitch:[...starters],bench:[...subs],status:'live',half:1,clockSeconds:0,runningSince:Date.now(),ourScore:0,theirScore:0,events:[],createdAt:new Date().toISOString()};data.matches.push(m);data.activeMatchId=m.id;save();draftMatch=null;route='live';render()}

function renderLive(){const m=activeMatch();if(!m){setRoute('home');return}const s=settings();const ev=[...(m.events||[])].reverse().slice(0,12);app.innerHTML=`<main class="screen live"><header class="topbar"><button class="icon-btn" data-route="home">‹</button><div class="wordmark">Live Match</div><button class="icon-btn" data-route="settings">⚙</button></header><section class="scoreboard"><div class="period">${m.half===1?'FIRST HALF':m.half===2?'SECOND HALF':'FULL TIME'}</div><div class="score-teams"><div class="score-team">${crestHtml(s.shortName||initials(s.clubName),s.homePrimary,s.homeSecondary,'small')}<strong>${esc(s.shortName||s.clubName)}</strong></div><div><div class="score">${m.ourScore}–${m.theirScore}</div><div class="clock" id="liveClock">00:00</div></div><div class="score-team">${crestHtml(m.oppAbbr,m.oppPrimary,m.oppSecondary,'small')}<strong>${esc(m.opponent)}</strong></div></div></section><section class="live-events">${ev.length?ev.map(e=>eventRow(e,m)).join(''):'<div class="empty">Match events will appear here.</div>'}</section><section class="live-actions"><button class="goal-btn" id="ourGoal">⚽ Goal</button><button class="sub-btn" id="substitution">↔ Substitution</button><button class="opp-goal-btn" id="oppGoal">⚽ Opposition Goal</button></section><section class="utility-row"><button id="timerToggle">${m.runningSince?'Pause':'Start'} clock</button><button id="halfAction">${m.half===1?'Half Time':m.half===2?'Full Time':'Result'}</button><button id="undoEvent">Undo</button></section>${nav('')}</main>`;updateClockDom();qs('#ourGoal').onclick=()=>openGoalFlow();qs('#substitution').onclick=()=>openSubFlow();qs('#oppGoal').onclick=()=>recordOpponentGoal();qs('#timerToggle').onclick=()=>{if(m.runningSince)pauseClock(m);else startClock(m);renderLive()};qs('#halfAction').onclick=()=>{if(m.half===1){pauseClock(m);m.half=2;m.clockSeconds=0;m.runningSince=null;save();toast('Half time · start the second half when ready');renderLive()}else if(m.half===2)finishMatch();else setRoute('result')};qs('#undoEvent').onclick=undoEvent}
function eventRow(e,m){const minute=`${e.minute}'`;if(e.type==='our_goal'){const p=playerBy(e.scorerId),name=e.goalType==='Own Goal'?'Own goal':p?.name||'Goal';return `<div class="event"><time>${minute}</time><span>⚽ ${esc(name)}${e.goalType==='Penalty'?' (PEN)':''}${e.assistId?`<small> · Assist: ${esc(playerBy(e.assistId)?.name||'')}</small>`:''}</span><span class="event-score">${e.scoreAfter||''}</span></div>`}if(e.type==='opp_goal')return `<div class="event"><time>${minute}</time><span>⚽ ${esc(m.opponent)}</span><span class="event-score">${e.scoreAfter||''}</span></div>`;if(e.type==='sub')return `<div class="event"><time>${minute}</time><span>↔ ${esc(playerBy(e.offId)?.name||'')} ↓ · ${esc(playerBy(e.onId)?.name||'')} ↑</span><span></span></div>`;return''}
function openGoalFlow(){const m=activeMatch();goalFlow={step:1,scorerId:null,goalType:null,assistId:null};renderGoalFlow(m)}
function renderGoalFlow(m){const f=goalFlow;let content='';if(f.step===1){content=`<h3>Who scored?</h3><div class="action-grid">${m.onPitch.map(pid=>`<button class="action-tile ${f.scorerId===pid?'selected':''}" data-scorer="${pid}">${tileHtml(playerBy(pid),false)}</button>`).join('')}</div>`}else if(f.step===2){content=`<h3>Goal type</h3><div class="goal-type-grid">${['Normal','Penalty','Own Goal'].map((x,i)=>`<button class="goal-type ${f.goalType===x?'selected':''}" data-goal-type="${x}"><span>${i===0?'⚽':i===1?'◫':'◉'}</span>${x}</button>`).join('')}</div>`}else{const assists=m.onPitch.filter(pid=>pid!==f.scorerId);content=`<h3>Assisted by? <span class="muted">optional</span></h3><div class="action-grid"><button class="action-tile selected" data-assist="none"><div class="no-assist">∅<br><small>No assist</small></div></button>${assists.map(pid=>`<button class="action-tile" data-assist="${pid}">${tileHtml(playerBy(pid),false)}</button>`).join('')}</div>`}
 openOverlay(`<div class="modal"><div class="modal-head"><h2>Record Our Goal</h2><button class="icon-btn" data-close-overlay>×</button></div><div class="modal-body"><div class="flow-steps">${[1,2,3].map((n,i)=>`<div class="flow-step ${f.step===n?'active':''}"><i>${n}</i>${['Scorer','Goal Type','Assist'][i]}</div>`).join('')}</div>${content}<div class="flow-actions"><button class="secondary-btn" id="goalBack">${f.step===1?'Cancel':'Back'}</button><button class="primary-btn" id="goalNext">${f.step===3?'Record Goal':'Next'}</button></div></div></div>`);qsa('[data-scorer]').forEach(b=>b.onclick=()=>{f.scorerId=b.dataset.scorer;qsa('[data-scorer]').forEach(x=>x.classList.toggle('selected',x===b))});qsa('[data-goal-type]').forEach(b=>b.onclick=()=>{f.goalType=b.dataset.goalType;qsa('[data-goal-type]').forEach(x=>x.classList.toggle('selected',x===b))});qsa('[data-assist]').forEach(b=>b.onclick=()=>{f.assistId=b.dataset.assist==='none'?null:b.dataset.assist;qsa('[data-assist]').forEach(x=>x.classList.toggle('selected',x===b))});qs('#goalBack').onclick=()=>{if(f.step===1)closeOverlay();else{f.step--;renderGoalFlow(m)}};qs('#goalNext').onclick=()=>{if(f.step===1){if(!f.scorerId){toast('Select a scorer');return}f.step=2;renderGoalFlow(m)}else if(f.step===2){if(!f.goalType){toast('Select the goal type');return}if(f.goalType==='Own Goal'){f.scorerId=null;f.assistId=null;recordOurGoal();return}f.step=3;renderGoalFlow(m)}else recordOurGoal()}}
function recordOurGoal(){const m=activeMatch(),f=goalFlow;const before=f.scorerId?goalCount(f.scorerId):0;m.ourScore++;const e={id:id(),type:'our_goal',minute:currentMinute(m),period:m.half,scorerId:f.scorerId,assistId:f.assistId,goalType:f.goalType,scoreAfter:`${m.ourScore}–${m.theirScore}`};m.events.push(e);save();closeOverlay();document.body.classList.add('flash');setTimeout(()=>document.body.classList.remove('flash'),430);showGoalCelebration(e,before)}
function showGoalCelebration(e,before){const p=playerBy(e.scorerId);const c=cardVars('home');openOverlay(`<div class="modal"><div class="celebration"><h2>GOAL!</h2>${p?`<div class="mini-card" style="--p:${c.p};--s:${c.s}"><div class="tile-number">${esc(p.number)}</div><div class="tile-name">${esc(p.name)}</div><div class="tile-pos">${esc(p.position)}</div></div>`:''}<h3>${esc(e.goalType==='Own Goal'?'Own Goal':p?.name||'Goal')}</h3><button class="primary-btn" id="goalContinue">Continue Match</button></div></div>`);qs('#goalContinue').onclick=()=>{closeOverlay();if(p){const after=before+1;let title=null;if(before===0)title='FIRST GOAL';else if([5,10,25,50].includes(after))title=`${after} GOALS`;if(title){const moment={id:id(),type:'goal',title,playerId:p.id,detail:before===0?'First GrassSTATory goal':`Reached ${after} career goals`,matchId:activeMatch()?.id,eventId:e.id,date:activeMatch()?.date||today()};data.moments.push(moment);save();showMoment(moment);return}}renderLive()}}
function showMoment(moment){const p=playerBy(moment.playerId),c=cardVars('home');openOverlay(`<div class="modal"><div class="moment-card"><div class="eyebrow">MOMENT ACHIEVED</div>${p?`<div class="mini-card" style="--p:${c.p};--s:${c.s};margin:14px auto;width:145px"><div class="tile-number">${esc(p.number)}</div><div class="tile-name">${esc(p.name)}</div><div class="tile-pos">${esc(p.position)}</div></div>`:''}<h2>${esc(moment.title)}</h2><h3>${esc(p?.name||settings().clubName)}</h3><p>${esc(moment.detail)}</p><div class="button-row"><button class="primary-btn" id="shareMoment">Share Moment</button><button class="secondary-btn" id="momentBack">Back to Match</button></div></div></div>`);qs('#momentBack').onclick=()=>{closeOverlay();renderLive()};qs('#shareMoment').onclick=()=>shareText(`${moment.title} · ${p?.name||settings().clubName} · GrassSTATory`)}
function recordOpponentGoal(){const m=activeMatch();m.theirScore++;m.events.push({id:id(),type:'opp_goal',minute:currentMinute(m),period:m.half,scoreAfter:`${m.ourScore}–${m.theirScore}`});save();toast('Opposition goal recorded');renderLive()}
function openSubFlow(){const m=activeMatch();if(!m.bench.length){toast('No substitutes available');return}subFlow={step:1,offId:null,onId:null};renderSubFlow(m)}
function renderSubFlow(m){const f=subFlow;const ids=f.step===1?m.onPitch:m.bench;openOverlay(`<div class="modal"><div class="modal-head"><h2>Substitution</h2><button class="icon-btn" data-close-overlay>×</button></div><div class="modal-body"><div class="flow-steps" style="grid-template-columns:repeat(2,1fr)">${[1,2].map((n,i)=>`<div class="flow-step ${f.step===n?'active':''}"><i>${n}</i>${i===0?'Player Off':'Player On'}</div>`).join('')}</div><h3>${f.step===1?'Who is coming off?':'Who is coming on?'}</h3><div class="action-grid">${ids.map(pid=>`<button class="action-tile" data-sub-player="${pid}">${tileHtml(playerBy(pid),false)}</button>`).join('')}</div><div class="flow-actions"><button class="secondary-btn" id="subBack">${f.step===1?'Cancel':'Back'}</button><button class="primary-btn" id="subNext">${f.step===2?'Record Sub':'Next'}</button></div></div></div>`);qsa('[data-sub-player]').forEach(b=>b.onclick=()=>{if(f.step===1)f.offId=b.dataset.subPlayer;else f.onId=b.dataset.subPlayer;qsa('[data-sub-player]').forEach(x=>x.classList.toggle('selected',x===b))});qs('#subBack').onclick=()=>{if(f.step===1)closeOverlay();else{f.step=1;renderSubFlow(m)}};qs('#subNext').onclick=()=>{if(f.step===1){if(!f.offId){toast('Select a player going off');return}f.step=2;renderSubFlow(m)}else{if(!f.onId){toast('Select a player coming on');return}const oi=m.onPitch.indexOf(f.offId),bi=m.bench.indexOf(f.onId);if(oi>=0)m.onPitch.splice(oi,1,f.onId);if(bi>=0)m.bench.splice(bi,1,f.offId);m.events.push({id:id(),type:'sub',minute:currentMinute(m),period:m.half,offId:f.offId,onId:f.onId});save();closeOverlay();toast(`${playerBy(f.offId)?.name} off · ${playerBy(f.onId)?.name} on`);renderLive()}}}
function undoEvent(){const m=activeMatch(),e=m.events.pop();if(!e){toast('Nothing to undo');return}if(e.type==='our_goal'){m.ourScore=Math.max(0,m.ourScore-1);data.moments=data.moments.filter(x=>x.eventId!==e.id)}else if(e.type==='opp_goal')m.theirScore=Math.max(0,m.theirScore-1);else if(e.type==='sub'){const oi=m.onPitch.indexOf(e.onId),bi=m.bench.indexOf(e.offId);if(oi>=0)m.onPitch.splice(oi,1,e.offId);if(bi>=0)m.bench.splice(bi,1,e.onId)}save();toast('Last event undone');renderLive()}
function finishMatch(){const m=activeMatch();pauseClock(m);m.status='completed';m.completedAt=new Date().toISOString();m.half=3;save();createAppearanceMoments(m);route='result';render()}
function createAppearanceMoments(m){const participants=new Set(m.starterIds);for(const e of m.events)if(e.type==='sub'&&e.onId)participants.add(e.onId);for(const pid of participants){const apps=appCount(pid);if([10,25,50,100].includes(apps)&&!data.moments.some(x=>x.type==='apps'&&x.playerId===pid&&x.value===apps)){data.moments.push({id:id(),type:'apps',title:`${apps} APPEARANCES`,playerId:pid,value:apps,detail:`Reached ${apps} appearances`,matchId:m.id,date:m.date})}}save()}
function renderResult(){const m=activeMatch()||completedMatches()[0];if(!m){setRoute('home');return}const s=settings();const events=[...(m.events||[])].filter(e=>['our_goal','opp_goal'].includes(e.type)).sort((a,b)=>a.minute-b.minute);app.innerHTML=`<main class="screen no-nav result-screen">${pagebar('Full Time','home','<button class="icon-btn" id="shareResult">↗</button>')}<section class="result-hero"><div class="period">FULL TIME</div><div class="result-teams"><div class="score-team">${crestHtml(s.shortName||initials(s.clubName),s.homePrimary,s.homeSecondary,'small')}<strong>${esc(s.clubName)}</strong></div><div class="score">${m.ourScore}–${m.theirScore}</div><div class="score-team">${crestHtml(m.oppAbbr,m.oppPrimary,m.oppSecondary,'small')}<strong>${esc(m.opponent)}</strong></div></div><p>${esc(m.competition)} · ${formatDate(m.date)}</p></section><section class="timeline">${events.length?events.map(e=>{const our=e.type==='our_goal',p=playerBy(e.scorerId);return `<div class="timeline-row"><time>${e.minute}'</time><div><strong>${our?esc(e.goalType==='Own Goal'?'Own goal':p?.name||'Goal'):esc(m.opponent)}</strong><small>${our&&e.goalType==='Penalty'?'Penalty · ':''}${our&&e.assistId?'Assist: '+esc(playerBy(e.assistId)?.name||''):our?'Our goal':'Opposition goal'}</small></div></div>`}).join(''):'<div class="empty">No goals recorded.</div>'}</section><div class="share-row"><button class="primary-btn" data-route="stats" data-tab="season">Match Stats</button><button class="secondary-btn" data-route="home">Back to Home</button></div></main>`;qs('#shareResult').onclick=()=>shareText(`${s.clubName} ${m.ourScore}-${m.theirScore} ${m.opponent} · ${m.competition}`)}

function renderStats(){const ts=teamStats(),ps=playerStats();let body='';if(statsTab==='players')body=`<div class="carousel-wrap"><div class="player-carousel" id="playerCarousel">${ps.map(x=>statsCard(x)).join('')}</div><div class="carousel-controls"><button id="prevCard">‹</button><button id="nextCard">›</button></div></div>`;else if(statsTab==='season')body=`<div class="stat-summary"><div class="stat-box"><strong>${ts.played}</strong><span>Played</span></div><div class="stat-box"><strong>${ts.w}</strong><span>Won</span></div><div class="stat-box"><strong>${ts.d}</strong><span>Drawn</span></div><div class="stat-box"><strong>${ts.l}</strong><span>Lost</span></div><div class="stat-box"><strong>${ts.gf}</strong><span>Goals For</span></div><div class="stat-box"><strong>${ts.ga}</strong><span>Against</span></div></div><div class="settings-card" style="margin-top:12px"><h3>Season story</h3><p>${ts.played?`${ts.w} wins from ${ts.played} matches · ${ts.gf} goals scored.`:'Your season story will build as matches are completed.'}</p></div>`;else body=`<div class="moments-grid">${data.moments.length?[...data.moments].reverse().map(m=>{const p=playerBy(m.playerId);return `<article class="settings-card"><span class="eyebrow">${esc(m.title)}</span><h3>${esc(p?.name||settings().clubName)}</h3><p>${esc(m.detail)}</p><small class="muted">${formatDate(m.date)}</small></article>`}).join(''):'<div class="empty surface">Moments will appear automatically as the season grows.</div>'}</div>`;
 app.innerHTML=`<main class="screen">${pagebar('Stats','home')}<section class="stats-wrap"><div class="tabs"><button data-stats-tab="players" class="${statsTab==='players'?'active':''}">Player Stats</button><button data-stats-tab="season" class="${statsTab==='season'?'active':''}">Season Stats</button><button data-stats-tab="moments" class="${statsTab==='moments'?'active':''}">Moments</button></div>${body}</section>${nav('stats')}</main>`;qsa('[data-stats-tab]').forEach(b=>b.onclick=()=>{statsTab=b.dataset.statsTab;renderStats()});if(statsTab==='players'){const car=qs('#playerCarousel');qs('#prevCard').onclick=()=>car.scrollBy({left:-car.clientWidth*.65,behavior:'smooth'});qs('#nextCard').onclick=()=>car.scrollBy({left:car.clientWidth*.65,behavior:'smooth'});let down=false,x=0,left=0;car.onpointerdown=e=>{down=true;x=e.clientX;left=car.scrollLeft;car.setPointerCapture(e.pointerId)};car.onpointermove=e=>{if(down)car.scrollLeft=left-(e.clientX-x)};car.onpointerup=()=>down=false}}
function statsCard(x){const c=cardVars('home'),p=x.p;return `<article class="stats-card" style="--p:${c.p};--s:${c.s}"><div class="sclub">${esc(settings().clubName.toUpperCase())}</div><div class="sn">${esc(p.number||'–')}</div><div class="sname">${esc(p.name)}</div><div class="spos">${esc(p.position)}</div><div class="sstats"><div><b>${x.goals}</b><span>GOALS</span></div><div><b>${x.assists}</b><span>ASSISTS</span></div><div><b>${x.apps}</b><span>APPS</span></div></div></article>`}
function renderSettings(){const s=settings();app.innerHTML=`<main class="screen">${pagebar('Settings','home')}<section class="stack"><div class="settings-list"><article class="settings-card"><h3>${esc(s.clubName)}</h3><p>${esc(s.ageGroup)} · ${esc(s.season)} · ${s.matchFormat}v${s.matchFormat}</p><button class="secondary-btn" id="editClub">Edit club details</button></article><article class="settings-card"><h3>Reset / Start Again</h3><p>Deletes this build's club, players, matches, stats and Moments from this browser and returns to first use.</p><button class="secondary-btn danger-btn" id="resetApp">Reset app</button></article><article class="settings-card"><h3>GrassSTATory</h3><p>Premium prototype · v${VERSION}<br>Local browser storage only. No account/backend yet.</p></article></div></section>${nav('settings')}</main>`;qs('#editClub').onclick=()=>{onboardStep=1;route='onboarding';render()};qs('#resetApp').onclick=()=>{if(confirm('Reset GrassSTATory and permanently delete this prototype data from this browser?'))reset()}}

function openOverlay(html){overlay.innerHTML=html;overlay.hidden=false;document.body.style.overflow='hidden';qsa('[data-close-overlay]',overlay).forEach(x=>x.onclick=closeOverlay)}
function closeOverlay(){overlay.hidden=true;overlay.innerHTML='';document.body.style.overflow=''}
function shareText(text){if(navigator.share)navigator.share({title:'GrassSTATory',text}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>toast('Copied to clipboard'));else toast(text)}
function openReport(id){data.activeMatchId=id;save();setRoute('result')}
function wireReports(){qsa('[data-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.report))}
function wireCommon(){qsa('[data-route]').forEach(b=>b.onclick=()=>{if(b.dataset.tab)statsTab=b.dataset.tab;setRoute(b.dataset.route)});if(new URLSearchParams(location.search).get('reset')==='1'){history.replaceState(null,'',location.pathname);reset()}}

render();
})();
